### ISSUE TITLE
Prototype Triage

### ISSUE THREAD

**Issue by alyssadelaine** [NASA-IMPACT/nasa-apt#124]
We have our prototype demo this Wednesday, May 8, and we still have a lot we need to do. I would like for each of us to complete everything on our section of this list by tomorrow so that we can move on to final touches and making sure everything is ready for the demo.

@ricardomestre 

- [x] Review [Contacts PR](https://github.com/developmentseed/nasa-apt/pull/114)
- [x] [Navigation between steps](https://github.com/developmentseed/nasa-apt/issues/97)

@dereklieu 

- [x] Frontend/Editor functionality for References: Modal/insert
- [x] [Step 7: Look at all the references and modify as needed](https://github.com/developmentseed/nasa-apt/issues/109)

@alyssadelaine 

- [x] [Serialization for References](https://github.com/developmentseed/nasa-apt/issues/111)
- [x] Finish [markup PR](https://github.com/developmentseed/nasa-apt/pull/120)
- [x] Any necessary changes to HTML docker image pending testing
- [x] Review [HTML and PDF generation on the Documents page](https://github.com/developmentseed/nasa-apt/issues/122)

@sharkinsspatial 

- [x] [Preview/”Read Only” Page in HTML and PDF](https://github.com/developmentseed/nasa-apt/issues/123)
- [x] Review [Docker->ECS PR](https://github.com/developmentseed/nasa-apt/pull/86)
- [x] [Add buttons for HTML and PDF generation on the Documents page](https://github.com/developmentseed/nasa-apt/issues/122)
- [x] [Implement loading indicator for Preview](https://github.com/developmentseed/nasa-apt/issues/107)
- [x] [“Documents” should be main page](https://github.com/developmentseed/nasa-apt/issues/121)

Whoever has time:
- [x] [Captioning of images](https://github.com/developmentseed/nasa-apt/issues/49)
