### ISSUE TITLE
Support `unicode-mathematics` and handle all special characters

### ISSUE THREAD

**Issue by alyssadelaine** [NASA-IMPACT/nasa-apt#176]
Special characters like greek letters can be copied and pasted into the editors, but we don't yet have a way to deal with these in the LaTeX serialization code

### subtasks

- [ ] support unicode in the body of LaTeX doc and -> PDF pipeline
- [ ] support `unicode-mathematics` in LaTeX -> PDF pipeline
- [ ] enable `unicode-mathematics` in `react-katex` browser rendering
