### ISSUE TITLE
LaTeX template refinements

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/nasa-apt#221]
**LaTeX template refinements**
Alyssa is finalizing some documentation around current status and what is missing. This will be use to spec out the refinements to be implemented.

### subtasks

- [x] PR with documentation: #230
- [x] Handle escaping for initial empty LaTeX expression in equation editor. #14
- [x] Fix PDF export in local development environment #242 
- [ ] Handle all special characters #176
- [ ] Inline mathematical equations #180
- [ ] Failing gracefully (related to #177)
- [ ] Testing (ensuring serialization works accounting for edge cases, and that it works with the schema provided by the server).
- [x] Architectural improvements #248, #250, #251
