### ISSUE TITLE
Implement `/events` endpoint stage transitions (EPIC #355)

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#375]
The following events handling logic should be added to the `/events` endpoint: 

| Action: | Required `status`: | Conditions: | Granted to: | Next status: | Tasks: | 
| --------| ------------------ | ----------- | ----------- | ------------- | ------ | 
| request_closed_review | DRAFT | | owner | CLOSED_REVIEW_REQUESTED | | 
| cancel_closed_review_request | CLOSED_REVIEW_REQUESTED | | owner | DRAFT | |
| deny_closed_review_request | CLOSED_REVIEW_REQUESTED | | curator | DRAFT | payload must accept a comment detailing why the closed review request was denied. (see TODO: 1) | 
| accept_closed_review | CLOSED_REVIEW_REQUESTED | | curator | CLOSED_REVIEW | |
| open_review | CLOSED_REVIEW |  | curator | OPEN_REVIEW| | 
| request_publication | OPEN_REVIEW |  | Owner/curator | PUBLICATION_REQUESTED | |
| cancel_publication_request | PUBLICATION_REQUESTED | |  owner | OPEN_REVIEW |
| deny_publication_request | PUBLICATION_REQUESTED |  | curator | OPEN_REVIEW |payload must accept a comment detailing why the closed review request was denied.|
| accept_publication_request | PUBLICATION_REQUESTED | | curator | PUBLICATION |
| publish | PUBLICATION | All threads related to the AtbdVersion must be marked as resolved | owner | PUBLISHED | generate and store a pdf for both journal and regular versions|

## Other actions to implement through the `/events` endpoint: 
- [x] Mark review `Done` (only reviewers) (if all reviews are done, set Atbdversion to `OPEN_REVIEW`)
- [x] Bump minor version (author, owner) --> generate pdfs again

## TODO: 
1. [ ] How/where will the `deny_closed_review_request` comment payload be stored? 
2. [ ] Will review automatically be opened once all reviewers have marked their review as done? If so the implementation will be slightly more complex
