### ISSUE TITLE
Notifications to implement (EPIC #371)

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#378]
This issue serves as a source of truth for which notifications to implement. Notifications will always be in email, and cannot be customized by users at this moment. They also are not aggregate, at this moment. 

- [x] Notify reviewers when they get added to an AtbdVersion
- [x] Notify authors when they get added to an AtbdVersion
- [x] Notify author/new owner when AtbdVersion ownership gets transferred to them
- [x] Notify author/old owner when AtbdVersion ownership gets transferred from them to someone else (important for when curators perform the ownership transfer)
- [x] Notify all curators when owner requests closed review
- [x] Notify owner when curator accepts or denies closed review (see if it's possible to include the content of the rejection note, if possible, with the deny message)
- [x] Notify owner and authors when a new thread is created
- [x] Notify all users participating in a comment thread when a new comment is added to the thread
- [x] Notify all users participating in a comment thread when the thread is set to `resolved` [EDIT: `resolved` -->`CLOSED`]
- [x] Notify owner and authors when the AtbdVersion is transitioned to `OPEN_REVIEW`
- [x] Notify all curators when the owner requests publication
- [x] Notify owner when the curator approves or denies the request for publication
- [x] Notify owner, authors and reviewers when the document is set to `PUBLISHED`

### Should any of the following notifications be implemented?
- Notify all curators when a new document is created
- Notify authors when a new version is created
- Notify authors + owner when reviewers add a new comment
- Notify all curators when a reviewer changes their review status
