### ISSUE TITLE
S1: Further develop APT and provide workflow unit and integration testing 

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#524]
## Motivation

APT is in the final stages of development.  At this point the tool is ready for use by a small user group, but needs further improvements to increase user satisfaction.  Specific tasks (see success criteria) have been identified as highest priority for completion.

## Description

The tasks include the items listed in the Success Criteria  below

## Success Criteria
- [x] Full testing of MCP production APT and bugs/fixes identified and prioritized
- [x] interface contains updated text and updated user guide(s)
- [x] Users can mention other collaborators in comments and those users are notified of the comment
- [ ] Several of the highest priority unit and integration tests are designed and implemented
- [x] Users can complete an ATBD without needing to publish in the journal
- [ ] Users can access PDFs of previous version in a user-friendly format
- [x] Highest priority bug fixes and minor improvements are completed

## Milestone Statement

S1: Further development of APT and provide workflow unit and integration testing to ensure reliable operation of APT for existing and new users.

## Supporting Stories
Thread Mentions
- [x] #456 

Unit/Integration Tests
- [x] #528 
- [x] #529 

Complete Workflow Step
- [x] #480 

Users have an improved interface to view version history and download past PDFs
- [x] #500 
- [x] #527 
- [x] #508 

Updated User Guide and Text
- [x] #510 

Addressing User Feedback
- [ ] Tickets TBD
