### ISSUE TITLE
S2:  Increase use of APT by science teams so they can effectively create, author, and review their ATBD

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#525]
## Motivation

We can not simply make APT functional and leave users unsupported.  This milestone is all the effort needed to ensure the APT users have the resources needed including assistance and training.

## Success Criteria
- [x] TEMPO and OPERA users are approved, trained and have ATBDs started
- [x] GEDI accounts are working
- [x] GEDI journal PDFs are completed and provided to authors for journal submission step
- [x] APT training video completed and placed in APT
- [x] AGU and AMS abstracts submitted
- [x] APT Bookmark designed for AGU/AMS

## Milestone Statement

S2: Increase use of APT by science teams and ensure users can effectively create, author, and review their ATBD leading to an increase in public ATBDs within APT.

## Supporting Stories

- [x] #522
