### ISSUE TITLE
Update and improve user guide

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#530]
### Description: 
Update all training materials with new figures and text so users have accurate support materials.

[User Guide](https://docs.google.com/document/d/1mImHjM0GTrjlcGYTJOvx0X4u-dNgtFt3Rvi-EJNdyYQ/edit#)

### Tasks:
- [x] Produce updated user guide  (Ashely - 1pts; Camille - 1pts)
- [x] Be sure to include new features, templates, etc.
- [x] Update all figures
- [x] create new markdown file and send to devseed

### Acceptance Criteria:
- [ ] Updated user guide completed and available on the APT

**Comment by bwbaker1** [comment]
@wrynearson Here is the updated user guide markdown file. It is ready to go. 

[APT_UserGuide.md](https://github.com/NASA-IMPACT/nasa-apt/files/11801187/APT_UserGuide.md)

**Comment by wrynearson** [comment]
This will be on staging once we review and merge https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/508
