### ISSUE TITLE
AGU and AMS abstracts

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#531]
### Description:
Share APT at major conferences to increase knowledge of APT's function and use.

### Tasks:
- [x] Develop AGU abstract, associated STI, and submit to AGU (2 pt)
- [x] Develop AMS abstract, associated STI, and submit to AMS (2 pt)

### Acceptance Criteria:
- [x] Abstract submitted to AGU
- [x] Abstract submitted to AMS

**Comment by bwbaker1** [comment]
Upon initial look at AMS sessions, maybe APT will fit in the "[39th Conference on Environmental Technologies](https://annual.ametsoc.org/index.cfm/2023/program-events/conferences-and-symposia/39th-conference-on-environmental-information-processing-technologies/)." I think we may have to get creative at AMS.

**Comment by deborahUAH** [comment]
Decision made to not propose to AGU or AMS this year as we presented last year and no significant new information to report.
