### ISSUE TITLE
APT Testing

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#533]
### Description: 
Test MCP production to detect bugs and needed fixes that will enhance the use of APT.

### Tasks:
- [x] Test MCP production using multiple browsers and operating systems
- [x] Describe and document all needing bug fixes and and other helpful feedback 
- [x] Check if collaborators get notifications when added to a document (also, needs text stating they have been added).
- [x] Determine who is the email sender for the curator.
- [x] Check if curators can see what emails are generated. 
- [x] Double-check all HTML content looks correct.  
- [x] Determine exactly what the curator can see on the dashboard (e.g., can they see who the reviewers are)?

### Acceptance Criteria:
- [x] APT MCP production completely and thoroughly tested

**Comment by bwbaker1** [comment]
Needs testing as of May 16, 2023
