### ISSUE TITLE
Complete OpsCon

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#534]
### Description:
Complete Con Ops to provide ESDIS and NGAP with needed details on APT's functionality and operation in MCP. Update all figures and text to match the current interface. 

### Tasks:
- [ ] Update all figures and text to match current interface (3 pt)
- [ ] Address all previous ESDIS comments (2 pt)
- [ ] Complete all sections of the report (4 pt)
- [ ] Deliver completed report to ESDIS for comments and respond to these comments (3 pt)

### Acceptance Criteria:
- [ ] Completed Con Ops document.

**Comment by deborahUAH** [comment]
added to FY23.1 for completion in Sprint 1 and 2
