### ISSUE TITLE
Develop Curator's Guide

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#537]
### Description:
APT needs a **detailed and clear document** describing the role and actions of a curator. 

### Tasks:
- [x] Identify all necessary curator actions (2 pt)
- [x] outline document structure (1 pt)
- [x] Draft a document describing actions with examples (i.e., guide) (4 pt)
- [x] Send draft document to team and others at IMPACT for review; need to make sure the document is clear and readable. (2 pt)
- [x] Make edits based on team review (2 pt)
- [x] Share document with ESDIS to gain feedback on curator role (2 pt)

### Acceptance Criteria:
- [x] Completed Curator's Guide document

**Comment by deborahUAH** [comment]
[Curator document draft started](https://docs.google.com/document/d/1TB0Yy8_QqrO9zDvcgIJODLxLnpHH5TR3mKlp4OHhyUk/edit#).  @bwbaker1 please review and add to the document per your understanding of the role and actions. We can meet later to discuss and edit the guide.  I especially could use help with screen captures of curator actions in the Curator Activity Descriptions section.

**Comment by deborahUAH** [comment]
rough outline completed. Document will be filled in during Q1 of FY23 sprint 1

**Comment by bwbaker1** [comment]
@deborahUAH 

[First draft](https://docs.google.com/document/d/1TB0Yy8_QqrO9zDvcgIJODLxLnpHH5TR3mKlp4OHhyUk/edit#heading=h.rlpxijyv8w9u). This needs review.

**Comment by deborahUAH** [comment]
Curator guide is completed.  One addition remains that requires a fix to APT first to get a screen grab needed for the document.  Once image is placed in document, the next activity (placement in the APT for curator view only) can be completed using another ticket for devseed work.
@bwbaker1 @wrynearson

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Closing this ticket (last screen grab added). Will open a new ticket to add this guide into APT.
