### ISSUE TITLE
Prepare TEMPO and OPERA users and get them started on ATBDs

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#538]
**EPIC: Increase APT Usage**

Description: Both TEMPO and OPERA scientists need to create ATBDs using APT per project requirements. Now that APT is in MCP production environment, the authors can begin work. APT team needs to support the needs of these scientists by introducing APT, training users as needed and answering questions.

**Tasks:**

- [x] Introductory meeting with TEMPO and GEDI
- [x] Approve all necessary accounts
- [x] Provide user training

**Acceptance Criteria:**

- [x] TEMPO and OPERA authors have approved accounts
- [ ] TEMPO ATBDs created and in authoring stage
- [x] TEMPO training session completed
- [ ] OPERA ATBDs created and in authoring stage
- [ ] OPERA training session completed

**Comment by bwbaker1** [comment]
**EPIC: Increase APT Usage**

Description: Both TEMPO and OPERA scientists need to create ATBDs using APT per project requirements. Now that APT is in MCP production environment, the authors can begin work. APT team needs to support the needs of these scientists by introducing APT, training users as needed and answering questions.

**Tasks:**
-[] Introductory meeting with TEMPO and GEDI
-[] Approve all necessary accounts
-[] Provide user training

**Acceptance Criteria:**
-[] TEMPO and OPERA authors have approved accounts
-[] TEMPO ATBDs created and in authoring stage
-[] TEMPO training session completed
-[] OPERA ATBDs created and in authoring stage
-[] OPERA training session completed
