### ISSUE TITLE
Prepare TEMPO and OPERA users and get them started on ATBDs

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#539]
### Description: 
Both TEMPO and OPERA scientists need to create ATBDs using APT per project requirements. Now that APT is in MCP production environment, the authors can begin work. APT team needs to support the needs of these scientists by introducing APT, training users as needed and answering questions.

### Tasks:
- [x] Introductory meeting with TEMPO and OPERA users to discuss APT (2 pt)
- [x] Approve all necessary accounts (2 pt)
- [x] Provide user training (2pt)

### Acceptance Criteria:
- [x] TEMPO and OPERA authors have approved accounts
- [ ] TEMPO ATBDs created and in authoring stage
- [x] TEMPO training session completed
- [x] OPERA ATBDs created and in authoring stage
- [x] OPERA training session completed

**Comment by deborahUAH** [comment]
Email sent on June 16th 2022
Sending this out to make sure I communicate with you about my APT introduction today to TEMPO scientists.
I met with 3 scientists who need to write ATBDs for TEMPO and  demonstrated all APT capabilities and gave an introduction to the purpose of APT 
Their timeline is a Jan 2023 TEMPO launch, readiness review in Oct/Nov - drafts must be completed by then

Their types of questions included (useful to understand so we can make APT guide and UI clearer):

- How can I reuse single item content in another ATBD?  copy/past?
- How do I duplicate an ATBD for use as a starting point for another ATBD (not a new version) that is only slightly different?
- How can one search through published ATBDs?  They want: DOI, Title, Author, year, summary text, keywords.
- They have an OMPS ATBD started in LaTex that they would like to put into APT right away. How well is the copy/paste working?
- Has anyone else done this so far?
- Are all sections required?

**Comment by deborahUAH** [comment]
On July 12th, Xiong Liu was notified that APT was available for use.  In addition, other users for TEMPO include Kelly Chance, Caroline Nowlan, and Gonzolo Gonzalez Abad.  These users have been recorded in the [APT User ](https://docs.google.com/spreadsheets/d/13pPNxi4XOJ4stWSQsIkggBQbOy-yl9OYPmXwynjfw4M/edit#gid=0)document

**Comment by deborahUAH** [comment]
As of Aug 1st, Caroline Nowlan had an account and started an ATBD (no title yet).  A follow-up email was sent today 8/10/2022 to offer training and assistance with getting the TEMPO team started on their ATBD.

**Comment by deborahUAH** [comment]
On Aug 10th I contacted TEMPO users and offered detailed introduction to APT and any needed assistance.  Response from Xiong 

> Thanks a lot for the follow-up. Sorry that we have not really get started to use the tool to work on ATBD yet other than just signing up for accounts, as some of us have been busy with other things or on vacation. But we have to get started soon in order to finish draft ATBDs within a few months before the deadline. A detailed training session would be very useful. But I do not know if it is better to be given after we get started or not. We will discuss about this at our group meeting tomorrow and will follow up with you.

- [x] follow up with Xiong Sept 1 to schedule training session
