### ISSUE TITLE
Assist GEDI users with completing ATBDs and getting them submitted to journal

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#540]
### Description: 
Assist GEDI users with completion of ATBDs and produce PDFs to be submitted to AGU ESS journal.

### Tasks:
- [x] Reinstate GEDI accounts into MCP (0.5 pt)
- [x] Check completed GEDI ATBDs for transition to publication (1.5 pt)
- [x] Deliver L4 ATBD PDF to AGU Earth Space and Science Journal (0.5 pt)
- [ ] Deliver L2 ATBD PDF to AGU Earth Space and Science Journal (0.5 pt)
- [x] Check GEDI completed L2 ATBD PDF for completion. 
- [ ] Notify Chelle when L2 ATBD ready for submission
- [x] Notify Chelle when L4 ATBD ready for submission.
- [x] Ensure L4 ATBD journal PDF can be downloaded for submission to PI/AGU

### Acceptance Criteria:
- [x] Confirm GEDI accounts are working
- [x]  L4 GEDI document submitted to AGU
- [ ]  L2 GEDI ATBD submitted to AGU

**Comment by deborahUAH** [comment]
Contacted GEDI L4 and L2B lead author (Jim Kellner) by email on 8/9/22.  The L4 ATBD is completed and has been submitted to the journal - Chelle was notified to look for it.  @bwbaker1, as curator, you should be able to move that ATBD from review to journal.  Let's discuss. 
Regarding L2B GEDI ATBD, the lead author (Hao Tang) reports that the ATBD is going through an internal review and editing now.  Hao commented that "the new system works much better than the previous version and many thanks for the updates".  
I will check back with both authors in 2 weeks.

**Comment by deborahUAH** [comment]
Email sent on 9/2/2022 to both authors to ask on progress and to inform them that I will be away for 3 weeks and to contact Brad and Aaron for problems or questions.

**Comment by bwbaker1** [comment]
@deborahUAH 

Has the GEDI L2B been submitted to the journal yet?  It seems there is only a few empty sections within the document in APT, and I know the L4 document was completed outside of APT.  Just curious if we can check off some more tasks for this issue.

**Comment by deborahUAH** [comment]
@bwbaker1   In last conversation with the scientist (Oct 21) he was going to get to it.  Can you send a reminder email to him to ask him about status?  He has since moved to Singapore.  Hao Tang <hao.tang@nus.edu.sg>.  I suggest saying we would like to assist in any way to help him with finishing the ATBD within APT.

**Comment by deborahUAH** [comment]
L4 ATBD has passed AGU ESS review.  Awaiting publication date.

**Comment by deborahUAH** [comment]
L4 GEDI ATBD accepted by AGU ESS.  see accepted article at https://doi.org/10.1029/2022EA002516
@bwbaker1  next step is to add content back into APT from the PDF online.

**Comment by bwbaker1** [comment]
Closing this issue since we have not heard back from GEDI L2 author(s).
