### ISSUE TITLE
APT journal article

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#541]
### Description: 
As part of increasing the science community's knowledge of APT and its capabilities, we need to publish an article in a peer reviewed journal.

### Tasks:
- [ ] Have team brainstorming session on potential outline
- [ ] Review potential journals
- [ ] Draft outline for journal article

### Acceptance Criteria: 
- [ ] Article outline (draft) delivered to team for review.

**Comment by bwbaker1** [comment]
@deborahUAH @kaulfusa Here is a rough outline of what I am initially thinking for a journal paper.  Feedback/suggestions are appreciated. Then I will start drafting/filling in details. 
[Draft link](https://docs.google.com/document/d/1FlJDX4a3U58shx38XrajYEm6J5HPECfWe17j18-quHQ/edit)

**Comment by bwbaker1** [comment]
We need to hold off on this issue until we determine the future of APT.
