### ISSUE TITLE
Update text when users cannot register an account due to Cognito permissions

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#549]
### Description
Need to test the entire account sign-up process on PROD.  

[Document](https://docs.google.com/document/d/1QPd-UWuxaqIa3ygTLjhA44q8-Zg0BLGZPGdxKmQRymA/edit)

### Tasks:
- [x] Run through the entire process of creating a new account.
- [x] Grab screenshots of each step in the process and put into a document.
- [ ] Send to team for review and determine any needed changes.

### Acceptance Criteria
- [ ] The sign-up process is smooth and very clear to users what is happening.

**Previous Issue - Aug 9, 2022**
Below is the message that a user receives when first signing up for APT, which is unclear and confusing to users.  The message seems to appear when a user attempts to login after confirming their account, but an administrator needs to first put the user into the correct Cognito group.  

The message should state the following: "A request has been placed for account approval."

![Image](https://user-images.githubusercontent.com/56319064/183752065-5399e1a6-c68a-489b-b95b-887f9a966f00.png)

**Comment by bwbaker1** [comment]
@aboydnw Rahul brought this to our attention today.  The current message isn't very helpful to users.

**Comment by aboydnw** [comment]
I _believe_ that this message is out-of-the-box from cognito and can't be modified. I think Daniel looked into this when we were making login improvements earlier this year. https://github.com/NASA-IMPACT/nasa-apt/issues/469

We should confirm this with devs, though.

cc @wrynearson

**Comment by kaulfusa** [comment]
Recreated in the staging environment (https://nasa-apt.surge.sh/) with username: kaulfusa, email: aaron.s.kaulfus@nasa.gov

Login attempt provide message "User does not exists" for this email.

**Comment by aboydnw** [comment]
The fix here is to adjust the verify email message coming from Cognito.

If possible, we should adjust the cognito message you receive when you click verify (or click it twice) to be more descriptive

**Comment by kaulfusa** [comment]
Cognito interface screenshot showing the message that can be changed. Happy to update with the new text.

<img width="1274" alt="Screen Shot 2022-08-10 at 10 55 56 AM" src="https://user-images.githubusercontent.com/43527413/183955651-f6893f0d-ccd4-43f3-9260-2cd00053b826.png">

**Comment by deborahUAH** [comment]
Email Subject:  "Verify your new APT account"
Email Message: "We have received your request for an APT account. <br> The account can only be verified once.  Please verify by clicking on {##Verify Email ##}.<br><br> If you have already clicked to verify your account, and you click again, you may see an error.  It can take up to 1 business day to approve your request.  Thank you for your patience.<br><br> Once verified, return to the <a href='https://www.earthdata.nasa.gov/apt/signin'>Algorithm Publication Tool</a> to sign in. <br><br>Please contact the APT team<email> if you have any problems.

**Comment by kaulfusa** [comment]
@deborahUAH @bwbaker1 I have updated the message text with that provided. Ready for verification.

**Comment by deborahUAH** [comment]
to test, I just signed up using my wxchicsr@gmail.com email.   I get this screen message 
<img width="176" alt="image" src="https://user-images.githubusercontent.com/88099931/185262426-f291609f-3916-4d53-8414-fb9e78e5eb4f.png">
and this email message: 
![IMG_1884](https://user-images.githubusercontent.com/88099931/185262832-3cfe60b0-cbd9-4d4f-86e9-996925051e50.PNG)
to which I received this confirmation 
![IMG_1883](https://user-images.githubusercontent.com/88099931/185263578-0fc1f51a-b2a1-441e-95b2-4658de59a7be.PNG)
when I click continue, I get the APT sign in page.  - but nothing tells me I can't sign in yet, so if I try, I get the error
<img width="185" alt="image" src="https://user-images.githubusercontent.com/88099931/185263169-dc5c641a-9443-4070-92da-2a23a42ab3c5.png">

**Comment by deborahUAH** [comment]
since the first message says "check your email, follow the instructions to verify your email address, and then click the button below to continue"  one is led to believe they will be approved when they see the confirmation.  Solution?  @kaulfusa does the user get an email when you approve them?  if so, then our message should say to wait to sign in until they receive the email saying they have been approved?  Will this fix the problem?  @aboydnw @wrynearson any other suggestions?  I notice the error message has changed to "User cannot be confirmed, do not refresh the confirmation page" (different from above).  If it can be altered, should we change to "User is not yet confirmed". ?

**Comment by aboydnw** [comment]
Update from this week's checkin: we were not able to replicate this final error message on the call. Deborah to try and replicate on her device.

**Comment by deborahUAH** [comment]
adding this issue to FY23.1 to finish checking and improving the signup information

**Comment by wrynearson** [comment]
@naomatheus can you check if updating this text is possible in AWS Cognito? We seem to think that this text is fixed by Amazon and that we can't change it – I'd like to be sure of that.

**Comment by wrynearson** [comment]
I'm closing this because we can't find a way to change the text. cc: @deborahUAH @bwbaker1
