### ISSUE TITLE
copy/create DEMO ATBD

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#552]
### Description:
The DEMO ATBD needs to be re-done since it was accidentally deleted.  DevSeed will attempt to recover the original from UAH PROD, if this isn't possible, the ATBD will need to be copied over from an old PDF version.  

This ATBD has now been accepted for publication through AGU ESS: https://doi.org/10.1029/2022EA002516

### Tasks:
- [x] Copy DEMO ATBD into MCP.  
- [x] Need to compare the officially accepted AGU ATBD with the DEMO to ensure consistency.
- [x] Review PDF version **(ATBD currently not downloading, so cannot check PDF version yet)**
- [x] Add green copy of manuscript to PROD using PDF upload (waiting to hear back from authors)

### Acceptance Criteria:
 - [x] Published DEMO ATBD to MCP (**DevSeed will let us know when finished with search and discovery fix, then we can publish**)

**Comment by aboydnw** [comment]
@bwbaker1 I checked with the team and unfortunately this is not easily migrated. The original migration script that was run when we moved over to MCP only worked because there were no documents (draft or published) in MCP at the time. Now that we have migrated over some documents, migrating over individual documents becomes much more complex. The least-cost solution would probably be using a PDF to re-create the ATBD.

**Comment by bwbaker1** [comment]
@aboydnw Can you look into one more option? Instead of migrating it over to MCP, is it possible to make it viewable from UAH PROD?  Copying content over from the PDF isn't a big deal (same as copying from within the tool), however I forgot how many long equations there are in that atbd.  It will take a very long time to figure out the Latex syntax for all of them.

**Comment by aboydnw** [comment]
@bwbaker1 sure thing, let me check on that

**Comment by aboydnw** [comment]
@bwbaker1 it's not really a quick thing to reveal the UAH stack via a UI. would this json that Leo pulled be close enough to what you are looking for? I looked through it and you can see the equations broken down by section and copy and paste the latex equation. https://drive.google.com/file/d/13vIyZ0jroD0uDNQ3U0xnKyY7LaXjylVN/view?usp=sharing

**Comment by bwbaker1** [comment]
@aboydnw No, I don't think this helps too much.  Its difficult to find the equations in the JSON and the syntax is a little different.  I will re-do the document from scratch.  I think the important thing moving forward is to make sure published documents cannot be deleted.  In that regard. I'm kind of glad this happened now and not later.

**Comment by wrynearson** [comment]
Confirming that this should wait until we've fixed #500, otherwise the ATBD won't be indexed for search.

cc: @naomatheus

**Comment by bwbaker1** [comment]
1) Need to the GEDI L4 published article to what is in APT.  There may be a few needed updates.
2) Still waiting on the ability to download PDFs on PROD. 
3) Once 1 and 2 are done, will publish the Demo ATBD.

**Comment by wrynearson** [comment]
@deborahUAH @bwbaker1 you're now able to work on this now that n° 2 ☝ is implemented

**Comment by bwbaker1** [comment]
Demo is ready.  Now waiting on "Discussion" section to be added to general PDF before publishing #682

**Comment by bwbaker1** [comment]
Update: Adding the "Discussion" has been deprioritized for now because it would require too much time/effort when the focus needs to be on PDF upload. Once the PDF upload is implemented, the workaround will be to use that to get this ATBD public on APT.

**Comment by wrynearson** [comment]
@bwbaker1 would leaving out the `discussion` part in the document PDF download be a bigger negative point than the benefits of having a demo ATBD on production? Users could still see the `discussion` in the HTML view mode, which is what I'd assume we'd like to be showing off to the users of the tool. You all are the ATBD experts though, so I'll leave this decision for your side

**Comment by bwbaker1** [comment]
@wrynearson Let's discuss this more at our tagup 5/15. It will be easier to give you more context then.
