### ISSUE TITLE
DOIs not showing up in references with bib imports

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#583]
### Description: 
@wrynearson @naomatheus @aboydnw User submitted a bug report (see below) stating that BibTeX imports do not map DOIs into the reference section.  This will for sure frustrate users since this could result in a lot of manual input on their part. 

### Tasks:
- [ ] Identify the issue of reference DOIs not being correctly mapped when BibTeX imports. 
- [ ] Identify any other reference parts not correctly mapping for BibTeX imports

### Acceptance Criteria:
- [ ] BibTeX imports working correctly and all reference information correctly mapped including DOIs.

![Image](https://user-images.githubusercontent.com/56319064/193126812-05747504-c347-4af6-858a-db9958dfc4b8.jpeg)

Here is an example:

**Bibtex file**
![Image](https://user-images.githubusercontent.com/56319064/193128285-6f906eb0-570d-409d-98c4-eb5fc2206ff3.jpeg)

**Imported Bibtex file** - note DOI is missing.

![Image](https://user-images.githubusercontent.com/56319064/193128448-cd20d1d2-a11a-45cc-8063-5385de292899.jpeg)

**Citation in APT** - note that this is not the DOI that is rendered.  

![Image](https://user-images.githubusercontent.com/56319064/193128887-24da39a9-b63c-461f-81f5-27156650cc99.jpeg)

**Comment by wrynearson** [comment]
Thanks @bwbaker1 , this one will have to wait, but when we have the capacity, we'll look into it.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH  It seems a few other fields are not mapping as well (online resource and isbn).

It was validated ([here](https://biblatex-linter.herokuapp.com/)).

**Comment by deborahUAH** [comment]
This is a P2 bug and must be handled in Q2 of FY23 - Prioritized as a must have in the list of things to do for Q2

**Comment by bwbaker1** [comment]
@wrynearson @aboydnw @deborahUAH  Here examples of other fields I noticed not showing up from a bibtex file: ISBN, publisher, and online resource.  Sorry I should have included examples before. 



![Image](https://user-images.githubusercontent.com/56319064/197288674-308317b3-87aa-4432-a2bb-576d200b08be.jpeg)



![Image](https://user-images.githubusercontent.com/56319064/197288815-c7930cf1-4543-47b9-92f0-9aa362a11ad0.jpeg)



![Image](https://user-images.githubusercontent.com/56319064/197288911-6a776913-9daa-478d-936b-2e6b588abe65.jpeg)

**Comment by deborahUAH** [comment]
In addition, a user has identified that there seems to be a character limit imposed on the "Publisher" field in the .bib reference import. It cuts off a lot of text in longer publisher names.

**Comment by bwbaker1** [comment]
@wrynearson @naomatheus 

Sorry, I didn't catch this before, but some words in the reference titles (when imported using BibTeX), have brackets around them.  This occurs even after using a BibTeX cleaner app on the file.  However, this does not occur for all references.  See a screenshot below.  I can send the .bib file via Slack if needed (the brackets does not appear within the file itself).  



![Image](https://user-images.githubusercontent.com/56319064/205724676-e9b58b1d-b6e9-4d62-9832-b3a6c147c306.png)
