### ISSUE TITLE
FY23.2 Objective 1: Improve APT functionality

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#588]
## Motivation

The tasks within this objective are designed to keep APT functioning while it is used by scientists and to make needed improvements for ESDIS transfer.

## Description

The work included in this Objective consists of 6 primary activities

- [x] test fixes and updates from PI22.4  and opensearch changes
- [x]  push open search fix
- [x]  push PI22.4 fixes and updates
- [ ]  update tool guidance and text
- [ ]  replace existing user guide with new content
- [x]  address high priority bugs in a timely manner (see tickets below)
- [x]  perform needed changes should MCP environment change and affect APT operation
- [ ]  update any utilized software, as needed, to keep APT safely and cleanly running
- [ ]  ensure APT agrees with AGU publication requirements

## Milestone Statement

PI23.1 APT Milestone remains unfinished.
Added to PI23.2

## Supporting Stories

- [x] #557 
- [x] #581 
- [x] #552 
- [x] #549
- [x] #545

**Comment by deborahUAH** [comment]
Sprint 1 progress:  PI22.4 changes pushed
