### ISSUE TITLE
FY23.2 Objective 2: Increase Knowledge and Use of APT

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#589]
## Motivation

During this second quarter, while APT is being used by the first group of scientists for ATBD construction, we need to ensure satisfactory use of APT and work towards increasing knowledge and understanding of APT for future users.

## Description

 This effort is to follow up with authors and assist as needed as scientists use APT to construct their ATBDs.  Users are recorded in this sheet.  
In addition, this Objective includes instructing newly funded teams on APT use and educating NASA program scientists about APT availability and access.
This quarter will include preparation for a NASA Webinar on APT and a meeting with program scientists to increase their knowledge of how APT works and the plans for transition to ESDIS.

To Do List: 
- [ ] contact all users each sprint to identify any issues or concerns
- [ ] Follow up on completion of GEDI ATBD journal submissions 
- [ ] write blurb on GEDI effort
- [ ] monitor ATBD construction, share with team any issues that everyone needs to know about -  APT user newsletter?
- [ ] create new demo videos
- [ ] create new APT introduction slideset 
- [ ] place training videos on tool for user access
- [ ] meet with program scientists to inform about APT availability and method of access
- [ ] prepare NASA Webinar on APT (to be scheduled in April or May)
- [ ] write journal article draft and share with Kaylin/Aaron

## Milestone Statement

PI23.1 APT Milestone, most tasks not completed.  Transitioned to Q2.

## Supporting Stories

- [x] #540 
- [x] #537 
- [x] #541 
- [x] #530 
- [x] #596 
- [x] #610 
- [x] #611

**Comment by deborahUAH** [comment]
Sprint1 progress:  active users supported.  Feedback documented in github and prioritized for fixes.  Curators guide completed
