### ISSUE TITLE
FY23.2 Objective 3:  Plan Transition of APT to EOSDIS

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#590]
## Motivation

APT will be transitioned out of IMPACT by the end of FY23.  The plan for this transition must be prepared and agreed-upon for work to begin

## Description

This objective covers all steps to design the plan for APT transition. This includes:

- [ ] Complete OpsCon and share with ESDIS
     [ ] Identify all roles and responsibilities for transition
     [ ] Address concerns of ESDIS
- [x] draft APT transition plan and share with ESDIS
- [x] Hold meeting to discuss with all parties a strategy for moving forward
- [ ] Complete and submit needed paperwork for NGAP transition
- [ ] All parties agree to/ sign off on transition plan
- [ ] Plan next steps and make tickets
 

## Milestone Statement

APT PI23.1  not completed, so moved to Q2

## Supporting Stories

- [x] #446 
- [x] #536
- [x] #534 
- [x] #535 
- [x] #530 
- [x] #608

**Comment by deborahUAH** [comment]
Completed Sprint 1:  held meeting with ESDIS;  drafted APT transition plan and submitted to ESDIS; 
Tasks for Sprint 2: Complete OpsCon; Address ESDIS concerns and questions

**Comment by bwbaker1** [comment]
@deborahUAH I figured out how to add the issue description to supporting stories.  You must add the issue links as a task list.  So just add "-[ ]" before the first linked issue. It does show a checklist box though.

**Comment by deborahUAH** [comment]
Thank you!
