### ISSUE TITLE
Story: User Help Videos

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#596]
### Description: 
This is an effort to ensure that users understand how to perform specific tasks within APT - from tasks related to using the tool to create ATBDs to the process of transitioning documents through the different stages (e.g., transitioning from draft to review). 

### Tasks:
- [x] Create demo videos that we know are needed to assist users.
- [x] Add to list of needed videos based on user and team feedback 

### Supporting Stories

- [x] #615 
- [x] #617  
- [x] #616 

### **Videos the are ready:**
Check when added to APT UI.
- [x] #617 - https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1
- [x] #616 - https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1

**Comment by bwbaker1** [comment]
Blocked until BibTeX files are uploaded appropriately - all fields populating correctly (e.g., DOI, Titles, etc.).

**Comment by wrynearson** [comment]
@naomatheus – see how we did it in SNWG. @deborahUAH said that using that approach (adding their Google Drive link into the help text) would work well.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/25919630/208445103-06808af8-dea5-46f9-ae6a-833462da0b99.png">

**Comment by bwbaker1** [comment]
@deborahUAH 

Here is the video.  Let me know if you are satisfied with it, and I will send it to DevSeed. 

https://user-images.githubusercontent.com/56319064/210560208-16979449-629e-47f1-8107-5c1c65cdc9a5.mov

**Comment by deborahUAH** [comment]
@bwbaker1 
I like the video content and the pace of presentation is good.  I do not like the automated voice.  Any reason for using this?  Can you make the video with your reading the script?

**Comment by bwbaker1** [comment]
@deborahUAH 

Used AI voice for pace and smoothness. I recorded audio first and listened to it as I made the screen recording.  Then merged audio and screen recording. I can add a third step and record myself reading the script (easy fix).  I will use the same three-step process as I make other help videos.
