### ISSUE TITLE
All in-text refs appear in PDF; All ref fields populate in reference section

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#601]
@wrynearson @naomatheus 

### Description: 
Not all citation fields are populating in the reference section (PDFs)

### Tasks:
- [x] The journal issue is not populating in the reference section.
- [x] Issue number should be in parentheses (example below: the issue number is 6, so it should be "(6)")
- [x] When more than one reference is added to a section, only the first reference entered shows up on the PDF.

### Acceptance Criteria: 
- [x] All citation input fields are correctly populated in the PDF downloads.
- [x] All references that a user enters should display on the PDF.

Current Reference Format (Note that the issue number does not display):

Hanson, B. (2014). AGU to Launch a New Open-Access Journal Spanning the Earth and Space Sciences. Remote Sensing and Environment, 95, 56-57.

Desired Format:
Hanson, B. (2014). AGU to Launch a New Open-Access Journal Spanning the Earth and Space Sciences. _Remote Sensing and Environment, 95_(6), 56-57.

Adding two references:

![Image](https://user-images.githubusercontent.com/56319064/208705488-37ecc0d0-a7e5-4777-bb50-884dcaba4743.png)

PDF result:

![Image](https://user-images.githubusercontent.com/56319064/208705664-13e1bf2b-7fe1-4164-a190-22cc78feb77b.png)

**Comment by naomatheus** [comment]
Opening a PR to address this issue. 
@bwbaker1 cc @wrynearson

**Comment by naomatheus** [comment]
Hey @bwbaker1 

Once the PR for this ticket is in staging, would you be comfortable checking the following criteria, to separate the italic formatting pointed out?

- All references that a user enters should display on the PDF, including multiple reference in a row.

I may end up proposing that we create a ticket for bold/italic formatting in general because bold/italic formatting is affected across the document and the fix will across the whole document, rather than a single part of the document.

**Comment by wrynearson** [comment]
@bwbaker1 this is fixed and is on staging for your team's review. cc @deborahUAH

**Comment by bwbaker1** [comment]
@wrynearson This is ready for production.

cc @deborahUAH

**Comment by wrynearson** [comment]
Thanks @bwbaker1. I'm not sure specifically which comments you're referring to. Could you please add them to this ticket so that we can give our developers better visibility?

**Comment by bwbaker1** [comment]
@wrynearson ☝️ I edited my previous comment - this is ready for production.  My other comments are related to another ticket.

**Comment by wrynearson** [comment]
This ticket can be closed for _Document_ PDF. When Journal PDF work is prioritized, we will implement the relevant changes and will list them in another ticket.
