### ISSUE TITLE
Heading Numbers

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#606]
@wrynearson @naomatheus 

### Description: 
Subheadings appear as normal text without section numbering.  Subheaders need a specific format.

### Tasks:
- [x] Number subheaders according to the specific section.

### Acceptance Criteria: 
- [x] Subheaders are numbered.

Current subheader: "New Subsection" line 139
Should be numbered as 7.3.1

![Image](https://user-images.githubusercontent.com/56319064/210821070-9fbc9491-545d-462f-b64c-a28249ea908e.png)

How subheader should look: 6.1.2 LIdar models for Canopy Directional Gap Probability and Vertical Profile Metrics

![Image](https://user-images.githubusercontent.com/56319064/210820892-96e39cb1-614a-4a32-9162-cc352080776a.png)

**Comment by naomatheus** [comment]
I will begin working on the italic in these subsections.

cc: @thenav56

**Comment by bwbaker1** [comment]
@naomatheus It seems like the new AGU format does not require bold or italic subheaders.  These just need to be numbered.  Sorry for the confusion.

**Comment by naomatheus** [comment]
Great, thanks for clarifying @bwbaker1 

Here are some examples. I will move this to in review.

**Subheading in the PDF**
![pdf-subheading](https://user-images.githubusercontent.com/25667086/213776541-7200783f-4c3f-415d-8639-67de8d8d8f71.png)

**Subheading in the interface**
![front-end-subheading](https://user-images.githubusercontent.com/25667086/213776659-21caae39-978a-492f-abfd-2e94ce9d9b60.png)


I am aware that the bold/italic issue is still unresolved.

**Comment by wrynearson** [comment]
Thank you @naomatheus for your work here. We will not implement https://github.com/NASA-IMPACT/nasa-apt/pull/605 because we will move the Journal PDF to the new PDF architecture (#622).

**Comment by wrynearson** [comment]
@sunu let's use this ticket to track the heading number requests.

Currently, we have pre-defined sections in APT. Counting the ATBD title as H1, we have H2–H4 level headers. We also have user-generated header that's one level lower than it's parent (either H3 or H4). Here's the structure:

H1 Title

1. (1) H2 Section Title
    1. (1.1) H3 Sub-section title
        1. (1.1.1) H4 Sub-sub-section title
    2. (1.2) H3 Sub-section title
        1. (1.2.1) H4 _user-defined section header_
2. (2) H2 Section Title
    4. (2.1) H3 _user-defined section header_
...

Here's how it's structured in the view mode.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/25919630/223393924-906fab67-7e83-429c-b060-66d4194fc2b5.png">

## Expected behavior:

- [ ] All heading numbers should align with their current `view` mode heading level (see screenshot ☝️)
- [ ] User-defined headings should be numbered (and have the level) one below their parent section (see screenshot for "Will's Heading" ☝️)

@bwbaker1 – please let me know if anything else is incorrect.

cc @batpad

**Comment by bwbaker1** [comment]
@wrynearson @sunu @frozenhelium Testing [results ](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=1371486832)(rows 18-22).

Row 18 is a little concerning because of the potential for missing content (Contacts). After this row is fixed, I think this ticket can be pushed to PROD. 

cc @deborahUAH @ashleyriddle92 @cw0045

**Comment by wrynearson** [comment]
@bwbaker1 is the issue that if:
1. A report exists with contacts
2. One contact is updated
3. The PDF doesn't properly capture the change, but the view mode does?

If so, I can open a new ticket for this issue since it doesn't seem to be related to the topic of this ticket (Heading Numbers)

**Comment by bwbaker1** [comment]
@wrynearson Yeah, the issue is that the PDF doesn't capture the change but the view mode does.  So it makes sense to have a separate ticket.
