### ISSUE TITLE
Long equations going over margins

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#607]
@wrynearson @naomatheus 

### Description: 
Long equations run over the page margins.  We need to determine if there is a way to create a line break (only in latex equations) or update user guide to stress that equations need to be as short as possible.

### Tasks:
- [ ] Determine if there is a way to add a "new line" character in the equation editors.
- [ ] Update the user guide to explain how to add new lines to equations. If there is no work around, update the user guide (perhaps add a message within the tool itself) stating that equations must be as short as possible to avoid overrunning equations.
- [ ] Update the equation LaTeX Cheatsheet icon to have text when hovered over (see image below). Currently, there is no text.

### Acceptance Criteria: 
- [ ] User guide and tool are updated to reflect how to handle long equations. 

Icon within equation editor should have text when hovered over. 

![Image](https://user-images.githubusercontent.com/56319064/210825788-0c1b714b-8a58-4f57-a6cf-699b8dd1f69c.png)

**Comment by wrynearson** [comment]
@bwbaker1 is this a problem only in the PDF generation or also in the frontend?

**Comment by bwbaker1** [comment]
@wrynearson This occurs in both the PDF and frontend.

**Comment by wrynearson** [comment]
Currently, in the equation editor, we have a warning that tells users that their equation may be too long to be rendered properly in the PDF (or the view mode).

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/25919630/221210242-70910363-b852-4b96-a781-c263aa70661b.png">

However, the user isn't prevented from inserting such a long equation, which results in view mode overflow and PDF clipping.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25919630/221210441-b8815645-f27e-4baa-8656-2a3a98cdadc8.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/25919630/221210491-816e1a5d-4901-4329-891c-815e881a957b.png">

According to [Stack Exchange](https://tex.stackexchange.com/questions/8936/how-to-break-a-long-equation), there are several methods to insert line breaks, but this could be tricky to do automatically. This ticket should be in a later sprint – I moved it to S4.

We should assess whether a technical solution or a user guidance solution is better.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This looks good. I think we can call this done. 

cc @deborahUAH

**Comment by wrynearson** [comment]
This is solved for the Document PDF. This will be implemented on the Journal PDF. This is _not_ implemented on the View mode.
