### ISSUE TITLE
Spike: Add user Cognito MFA

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#608]
### Description: 
As part of the NGAP transition, APT needs to require Cognito-based multi-factor authentication and authorization. 

### Tasks:
- [x] Determine necessary steps to enable MFA (see screenshot from Cognito below).
- [x] Review guidelines provided in [APT transition plan](https://docs.google.com/document/d/1ONsttOnATepem7HP4DNZatfyO3-Kyr_-dai5cIOULiE/edit#): [https://wiki.earthdata.nasa.gov/display/ESKB/AWS+Services+Approval+Status+Page](url)
- [ ] Notify users of change to sign-in
- [ ] Enable MFA. 

### Acceptance Criteria: 
- [ ] Users are notified of change
- [ ] MFA is enabled for all users to log into APT. 

Cognito MFA screenshot from APT staging.  

![Image](https://user-images.githubusercontent.com/56319064/211059997-64c3d8ad-1b1a-4206-8e07-39b6e99fac7b.png)

**Comment by wrynearson** [comment]
@frozenhelium will look into this from the frontend perspective. He'll ask any questions by Tuesday, Jan 24 so we can write implementable tickets by Wednesday, Jan 25.

**Comment by wrynearson** [comment]
@frozenhelium FYI that SMS won't be an option, only OTP

**Comment by frozenhelium** [comment]
@batpad @wrynearson 
### Amazon Cognito MFA using AWS Amplify
- We can use AWS Amplify to provide the MFA (we're already using this for our current authentication process)
- Once we enable MFA on Amazon Cognito using the console, we can configure the APT to work with MFA

#### Configuring MFA for a user
- When a user first signs in, we use the received one-time access token to generate the TOTP private key and present it to your user in text or QR code format.
- User have to configure their authenticator app and provides a TOTP for subsequent sign-in attempts.
- The app presents the TOTP to Amazon Cognito in MFA challenge responses.

#### We need to implement following features
- Associate the TOTP software token
	- When MFA is enabled, we can call `AssociateSoftwareToken` to get a unique shared secret key code for the user account. 
	- The private key can be used in TOTP-generating app such as Google Authenticator.
	- Authenticator will now generate time based codes which can be used as OTP token
- Verify the TOTP token
	- Request sample codes from the user and provide it to the Amazon Cognito service to confirm that the user is successfully generating TOTP codes
- Sign in with TOTP MFA
	- At this point, user signs in with the time-based one-time password.

More details: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-totp.html

**Comment by wrynearson** [comment]
Thanks @frozenhelium. I'm guessing that we would need to test locally and then on staging? Or is this something that we should skip to staging for? Or some combination (local frontend, staging backend)?

With the various time zones, try to let me know in advance if you need anything (changing staging cognito preferences, etc.) @naomatheus and I both have access to the AWS stack. cc: @batpad

**Comment by wrynearson** [comment]
If we need to make any design decisions to help users through this process, we can discuss those as well (e.g., if Cognito's instructions aren't clear, if a user loses access to their authenticator app, etc.)

**Comment by frozenhelium** [comment]
@wrynearson I'll figure out if we can easily test it in the local, If not we should be able to use the staging for testing as well.

**Comment by wrynearson** [comment]
OK, thanks @frozenhelium. I'll be out tomorrow, so if you need anything regarding AWS, please let me know today or let @naomatheus know so he can make any changes necessary.

**Comment by wrynearson** [comment]
@xhagrg @batpad @frozenhelium optional MFA (with authenticator apps) is on for the AWS Cognito staging pool. @frozenhelium will continue testing

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Is the current status "Review by IMPACT" just to test if the authentication/OTP works as expected on staging, or is this related to something else? 
We have tested using a few authenticators and haven't encountered any issues yet.

**Comment by wrynearson** [comment]
@bwbaker1 correct, this is to have your side confirm that everything is working properly with existing and new users adding MFA. We've tested this but we wanted to be cautious because we'll be pushing a user flow change with existing users on prod.

**Comment by deborahUAH** [comment]
@bwbaker1 please write up email content for notifying all active users of the change to MFA and the steps they need to take once it is implemented.  Once the email is sent to all users, we can then push to production.  Not before then. Users will be confused if the sign-in process changes without being warned.

**Comment by wrynearson** [comment]
We need to ensure MFA is set to optional in Cognito for user groups on prod, and we need to rename the QR code name to "APT".

@frozenhelium for the time being, can you add a "skip" option? We will then enforce MFA before transitioning to NGAP

**Comment by bwbaker1** [comment]
@wrynearson Is the only reason to initially set MFA as optional just to ensure users don't run into issues or is there some other reason?

We will be sending users an email on Friday (March 24th) regarding MFA, so we need to be very specific as to why it is currently optional. We also need to tell them exactly how to bypass MFA.  We want to ensure that this is not confusing to them.

cc @deborahUAH

**Comment by wrynearson** [comment]
Hi @bwbaker1, sorry for the confusion. We'll keep the MFA in the same state as when you tested it on staging.

Correct, our thought process was that if we are pushing a change to the user flow _and_ that change isn't technically required until we start the NGAP transition, then we could mark it as optional to allow for users to set up MFA when it worked best for them.

**Comment by bwbaker1** [comment]
@wrynearson MFA is required on staging, so how will it look if it is optional?  I need to know what to tell users to expect (i.e., can they just completely bypass configuring MFA?) Also, do we have a timeline of when they will be required to set it up? 
[Here ](https://docs.google.com/document/d/1aPoSFCm2cMvdbqRPHltHHlF6oTSAd9eZ58uLUfEkSRE/edit?usp=sharing) is the email that will be sent out (feel free to add comments).

cc @deborahUAH

**Comment by wrynearson** [comment]
@bwbaker1 MFA is required on staging from a frontend perspective. Technically we have MFA as optional within AWS settings on staging, but it would be required on production. The only difference in the fronted is that we could add a little "x" to close out of the prompt to set up MFA. 

However, agreed that adding any change at this point would be tight in terms of implementing and reviewing, so let's scrap that idea and proceed as originally planned (required MFA as of Wednesday the 29th on production).

I left a few comments on the draft email.

**Comment by wrynearson** [comment]
This is ready for production (enforcing MFA). cc @bwbaker1 let me know if you disagree 😄

**Comment by bwbaker1** [comment]
@wrynearson I think it is ready.
