### ISSUE TITLE
User notification emails and email content

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#609]
### Description: 
There is a need to determine when users (authors, reviewers, and curator(s)) get notification emails (e.g., new comment, added as contributor, etc.) and the content of these emails. 

https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit#gid=0  
https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=598514114

### Tasks:
- [x] Create a table that includes the following columns: role, notification type (e.g., new comment), and message (probably will be a working document)
- [x] Fill in the table with content.
- [x] All impact team members to thoroughly review table.
- [x] Submit the table to DevSeed for implementation within APT.

### Acceptance Criteria: 
- [x] Completed table submitted to DevSeed. 
- [ ] Notification implemented in APT

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH we used [this spreadsheet](https://docs.google.com/spreadsheets/d/1PjRF0ubkbl_sXa94KevtPfRcy10QHGSbaOdTDR5AOik/edit#gid=598514114&range=A1) for SNWG. If it's intuitive and appropriate, feel free to copy that framework for creating the content of APT notifications.

For us to be able to implement email notifications, we need to know:
1. Which action triggers an event (e.g., submitting a doc for review)
2. Knowing who to notify for that event (e.g., the document's collaborators, relevant reviewers)
3. The text of the email (we can have repeated text blocks and can incorporate some "content" of a document (e.g., the document comment in a thread mention email)

When thinking about these, keep in mind the _frequency_ of emails that are sent (users don't like to be spammed with emails). I'm happy to chat through this if you'd like.

Once the content is finalized, we can make a new ticket to add the content and functionality in.

**Comment by wrynearson** [comment]
@thenav56 This ticket will have the requested email notification triggers and content, but it needs to be finalized by NASA.

@deborahUAH and @bwbaker1, we will have some capacity this sprint to work on email notifications. Do you think that the [first link](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit#gid=0) is accurate so that @thenav56 could start working on this, or should we wait until you've confirmed the content in the [second link](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=598514114)?

**Comment by deborahUAH** [comment]
I am working on the notifications and will have them done tomorrow afternoon pacific time

**Comment by deborahUAH** [comment]
@wrynearson @thenav56  [This doc](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit?pli=1#gid=0) should have the needed notifications.   @bwbaker1 please review to check my work.  I have some questions that need to be addressed.   I combined the content of both docs and tried to think of any other notifications needed.  We can discuss further as you begin to implement.

**Comment by wrynearson** [comment]
Thank you @deborahUAH! We can talk through these the next time that we meet. I will review them and work with @thenav56 to implement them. From our experience with RGT, it is much easier for the developers to have a finalized list before going in and creating/editing email notifications. We can definitely make tweaks if needed – I'm just flagging this for hopefully having a smoother process.

**Comment by bwbaker1** [comment]
@deborahUAH We left some comments in this [document](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit?pli=1#gid=0) while reviewing these notifications. I guess we forgot to tag you in it. 
We can send this to DevSeed to implement after you review the our comments.

**Comment by bwbaker1** [comment]
@wrynearson Email notifications are ready to be implemented. See [document](https://docs.google.com/spreadsheets/d/1uJ6t7_EUFzxrbXQmxugdjq5i_8i9O7Zi8P-LfcAeLbs/edit#gid=0). You can ignore the column with our comments.

**Comment by wrynearson** [comment]
Thanks @bwbaker1, cc @thenav56

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this wasn't on the Miro board. We're assuming it's pretty high priority :)

**Comment by bwbaker1** [comment]
@wrynearson Yes, this needs to be on the board and is a high priority.

**Comment by wrynearson** [comment]
OK, I put it below Journal PDF stuff and above the homepage update ticket. @thenav56 please let move the complexity of the sticky if need be

**Comment by wrynearson** [comment]
@bwbaker1 this is ready on staging. I haven't had the chance to test this yet, so if you get to it today, please let me know if you experience any issues. Otherwise, I'll be testing this early next week.

**Comment by bwbaker1** [comment]
@wrynearson Great! We will start testing asap.

**Comment by wrynearson** [comment]
Hey @thenav56, here's updated text for how the new account email should look like:

> Hi "preferred username",
> 
> Your Algorithm Publication Tool (APT) account has been created. Please verify your account by clicking on [Verify Email](https://nasa-apt-api-staging.auth.us-east-1.amazoncognito.com/confirmUser?client_id=61286541mqtm9t680nnskdd3ii&user_name=76f49fd8-952b-44a9-9003-33d0b3bf1c45&confirmation_code=963234). Your account only needs to be verified once.
> 
> Please review the user agreement statement below, then access your APT account by clicking [here](https://nasa-apt.surge.sh/signin).
> 
> NASA ALGORITHM PUBLICATION TOOL (APT) POLICY / USER AGREEMENT STATEMENT NASA IT Consent Banner | NASA-SPEC-2669 Version 1.0
> 
> By accessing and using this information system, you acknowledge and consent to the following: You are accessing a U.S. Government information system, which includes:
> 
> (1) this computer; (2) this computer network; (3) all computers connected to this network including end user systems (4) all devices and storage media attached to this network or to any computer on this network; and (5) cloud and remote information services. This information system is provided for U.S. Government-authorized use only. You have no reasonable expectation of privacy regarding any communication transmitted through or data stored on this information system. At any time, and for any lawful purpose, the U.S. Government may monitor, intercept, search, and seize any communication or data transiting, stored on, or traveling to or from this information system. You are NOT authorized to process classified information on this information system. Unauthorized or improper use of this system may result in suspension or loss of access privileges, disciplinary action, and civil and/or criminal penalties.
> 
> By accepting APT account access, you acknowledge that you have read, understand, and agree to abide by the NASA APT POLICY / USER AGREEMENT STATEMENT as written above.
> 
> By accepting APT account access, you acknowledge that you have read, understand, and agree to abide by the APT Access Control Policy Statement as written in this document: https://docs.google.com/document/d/1zSNTAmC1LIFZh__Y5vIgP6VaxnZ4r9OO-jWBt0Lv08I/edit?usp=sharing
> 
> Sincerely,
> The NASA APT Team

cc @bwbaker1

**Comment by sunu** [comment]
@wrynearson We might have to limit the greeting to just `Hi,` since Cognito doesn't let us access `preferred_username` or `email` in the verification message template

**Comment by wrynearson** [comment]
@sunu how are we doing it in RGT then?

https://github.com/NASA-IMPACT/snwg-backend/blob/9c0831d0b9efd6f82668ef7c1fc33b6d0f4de649/app/email/email_templates.json#L4

**Comment by wrynearson** [comment]
OK, let's use `Dear APT user,` then as it's a bit more formal (which I think makes more sense given the body content of the email)

**Comment by wrynearson** [comment]
FYI @bwbaker1, when we send out the new emails that users are the lead author of a document, that email is triggered when the document is created. Because the user hasn't had time to rename the document, the email will say that they're the lead author of "Untitled Document". The link will still work.

We can see if there's a simple approach to fixing this, but we currently don't have any time-based email triggers.

cc @thenav56

**Comment by bwbaker1** [comment]
@wrynearson @thenav56  I think it is fine to leave it as it is. The link is the important thing for this notification.
Nice catch though.

**Comment by wrynearson** [comment]
@bwbaker1 I think we can close this ticket, but please let me know if we should keep it open

**Comment by bwbaker1** [comment]
@wrynearson We can close it. We can open a new ticket later on if we find any issues with the notifications.
