### ISSUE TITLE
Prepare for NASA APT Webinar

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#611]
### Description: 
To bring more awareness to APT, Jennifer Brennan has agreed to place APT on the NASA Webinar schedule.  Data TBD

### Tasks:
- [ ] meet with Jennifer to get on schedule
- [ ] prepare slide deck
- [ ] prepare demos
- [ ] prepare pre-webinar questions
- [ ] gather invited user list
- [ ] practice with Jennifer
- [ ] 2nd practice with Jennifer

### Acceptance Criteria: 
- [ ] Webinar scheduled and prepared for (to probably be given in FY24 Q1)

**Comment by deborahUAH** [comment]
APT webinar put on hold.  Not in this quarter. Putting issue back in backlog

**Comment by bwbaker1** [comment]
Closing for now.

**Comment by bwbaker1** [comment]
Reopening. Plan to have webinar later in fall, but we need to start preparing now.
