### ISSUE TITLE
Check version description text block

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#612]
@deborahUAH @naomatheus 

### Description: 
An unknown section, "1 Description", appears in both PDF downloads.  This section has the "Content Unavailable" placeholder text(see image below), and there does not seem to be anyway to add/edit this content.  @wrynearson suggested checking to see if this is actually the ATBD version description text block.  

### Tasks:
- [x] Determine what is causing the "1 Description" section in both PDF downloads. Check to see if it is related to the ATBD version description text block.
- [x] Discuss with team once the cause of this section is determined. 

### Acceptance Criteria: 
- [ ] The cause of the "1 Description" section is discussed with team and a decision is made for how to resolve this section.
- [ ] Resolution is implemented and works correctly when tested

###Example showing "1 Description" in PDF

![Image](https://user-images.githubusercontent.com/56319064/211317732-00a51274-0d61-4c71-974c-68f936995a45.png)

**Comment by bwbaker1** [comment]
@wrynearson @naomatheus @deborahUAH 

This is related to the version description.  So we probably need some solution if a user does not add any content into this field.  See below.

editing mode:


![Image](https://user-images.githubusercontent.com/56319064/211598960-8810c4c9-24a8-4f27-82a2-0eaff2ff0438.png)


viewing mode: 



![Image](https://user-images.githubusercontent.com/56319064/211599005-1e2f96df-6199-420a-9dbd-7d7f888365a1.png)


PDF:



![Image](https://user-images.githubusercontent.com/56319064/211599044-1d90e6c8-68f0-450c-b07b-7b7da6fd8996.png)

**Comment by deborahUAH** [comment]
1) The section needs to be called Version description in the PDFs
2) is it possible that if V1, the section is omitted from the PDFs but if any other version it is included and required?

**Comment by wrynearson** [comment]
Thanks for confirming our idea @bwbaker1. We can rename the section. I will check with the team to see if version-driven PDF structure modifications are possible, but I would image that is tricky. cc: @batpad

**Comment by naomatheus** [comment]
Correct, the "Description" header is the PDF title for the "Version Description" element.
They are now named the same. 

Regarding leaving out "Version Description" under specific ATBD version circumstances. I can confirm this is possible in the `journal` type ATBD. I'll update you when I can verify this is possible with the non-journal/`document` type ATBD.

[Reference PR ](https://github.com/NASA-IMPACT/nasa-apt/pull/628)

cc @wrynearson

**Comment by wrynearson** [comment]
This is fixed with the new PDF generation approach: https://github.com/NASA-IMPACT/nasa-apt/pull/638
