### ISSUE TITLE
Rich text editor does not work for tables

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#614]
@wrynearson @naomatheus @deborahUAH 

### Description: 
Users have the option to format table content using the rich text editor (e.g., bold, italics, etc.). This formatting appears correctly when viewing a document in HTML, however, it does not appear on either PDF types. 

### Tasks:
- [ ] Determine why table formatting does not render on PDFs.
- [ ] Resolve the issue so that tables have user defined formatting.  

### Acceptance Criteria: 
- [ ] All table formatting using the rich text editor (e.g., bold, italics, links, etc.) render correctly on both PDFs. 

###Example:
Table formatting in editing mode:

![Image](https://user-images.githubusercontent.com/56319064/211335477-8c606907-60da-48ea-a094-559714789c7a.png)

HTML rendered table:

![Image](https://user-images.githubusercontent.com/56319064/211335531-0fcb8fc3-d14f-4bc1-b8d1-c0bff64b1f05.png)

PDF rendered table:

![Image](https://user-images.githubusercontent.com/56319064/211335567-8b7087c9-e758-4600-9fc5-30b6dd312f8c.png)

**Comment by wrynearson** [comment]
This is probably a very tricky bug to fix with our current PDF generation technique. Our proposed change (which we're testing this week) will solve this bug. Tagging @thenav56 because he worked on PDF generation in SNWG.

**Comment by wrynearson** [comment]
This is fixed with the new PDF architecture #622
