### ISSUE TITLE
Create and Add Help video: BibTeX import

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#615]

**Comment by bwbaker1** [comment]
### Description: 
This help video will demonstrate how to use APT's BibTeX import feature and will be uploaded to APT PROD.

### Tasks:
- [x] Create a video that steps users through the process of creating and importing a BibTex file (references) in APT.
- [x] Upload video to this [folder](https://drive.google.com/drive/folders/1QYq75gh7RMKGi4tU1lnJBj9lx5paZ25e).
- [x] Submit the video to team for review.
- [x] Make edits based on feedback.
- [x] Share video link with DevSeed.

### Acceptance Criteria
- [x] Video is uploaded and working on PROD.

**Comment by wrynearson** [comment]
For DevSeed, once the video is finalized, we will need to add an info tooltip (pictured below) to the reference upload/edit section (2nd picture). Once the video is finalized, we can put the Google Drive video link into the new info tooltip.


![Image](https://user-images.githubusercontent.com/25919630/212892184-5087ae7a-078e-48ac-92a0-67fb186dd9b9.png)

![Image](https://user-images.githubusercontent.com/25919630/212892080-557a189d-8278-4c01-bf1c-c1dba344403c.png)

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Please review the new Bibtex help video [here](https://drive.google.com/drive/folders/109Lo3jC5CytNnuWhOoOR9UvhToA8cbZv).  Camille's narration is definitely better than the AI generated voice.

**Comment by deborahUAH** [comment]
The video voice over is great!  Good job Camille.  The only issue with the video is that the bibtex upload did not work correctly and the reference shown in the video is incorrectly formatted.  The date (1978) did not get added and there is an extra comma and other missing reference content.  Others will catch this.  Sorry to have to say this but the video needs to be reshot after first making sure the example you use is correctly done.  I also suggest typing a short sentence and then adding the reference so that the user can see how it looks in the UI.   Also, is it necessary to copy and paste?  I think one could select several references from something like mendeley and then export the bibtex and then clean/tidy.  Encourage users to check visually for completeness first (ie, are the essential fields all there?  in your example they are) and then check the references imported visually to see if correct after tidying.  In the case of the video they are not.

**Comment by bwbaker1** [comment]
The main issue is that the bibtex import still does not populate all of the reference fields (including the publication year).  After discussion with Deborah, we will keep the video "as is" for now and re-do it once the import aspect is fixed.  We will also incorporate the other suggestions/comments (e.g., encourage visual inspection of fields, etc.).

**Comment by wrynearson** [comment]
I have moved the implementation of this ticket to sprint 4. @frozenhelium will be able to add a tooltip (currently not on this page) and then link the video that @cw0045 made. If you re-upload the new video using the "manage versions" in Google Drive, we shouldn't have to change the URL once the new video is uploaded. If you don't use this feature, it's not a problem.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/25919630/221216561-604b5e17-98f0-4098-b176-f486f0b8bff6.png">

**Comment by wrynearson** [comment]
I have moved the implementation of this ticket to sprint 4. @frozenhelium will be able to add a tooltip (currently not on this page) and then link the video that @cw0045 made. If you re-upload the new video using the "manage versions" in Google Drive, we shouldn't have to change the URL once the new video is uploaded. If you don't use this feature, it's not a problem.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/25919630/221216561-604b5e17-98f0-4098-b176-f486f0b8bff6.png">

**Comment by bwbaker1** [comment]
We need to redo this video now that the BibTeX import feature is working correctly. This should only require a few tweaks to the script and re-recording it.  Should take ~hour. Moving to sprint 5.

**Comment by bwbaker1** [comment]
@wrynearson This video is now ready.

[Link](https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1) to video: Help Video: How to Import a Bibtex File.mov

**Comment by wrynearson** [comment]
Thanks @bwbaker1, added in https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/435/commits/a527fe9001603dd376079a4d1cf175f51a58195a
