### ISSUE TITLE
Help video: Login and Create a New ATBD

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#616]
### Description: 
This help video will demonstrate how to create a new document..

### Tasks:
- [x] Create a video that shows how to create a new document. 
- [x] Upload video to this [folder](https://drive.google.com/drive/folders/1QYq75gh7RMKGi4tU1lnJBj9lx5paZ25e).
- [x] Submit the video to team for review.
- [x] Make edits based on feedback.
- [x] Share video link with DevSeed.

### **VIDEO**
[Help Video: Login and Create a New ATBD](https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1)

### Acceptance Criteria
- [ ] Video is uploaded and working on PROD.

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH we'll need to think about where we'd put this video, as it covers multiple steps (logging in and creating a new document).

**Comment by bwbaker1** [comment]
@wrynearson Broke the original issue into two separate videos.  We will keep any videos to one-step to avoid having to figure out where to put the video.

**Comment by bwbaker1** [comment]
This has not been started yet.  It's a very straight forward video that should only take ~hour.
