### ISSUE TITLE
Help video: Managing Roles part 1 - How to add collaborators and change lead author

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#617]
### Description: 
This help video will demonstrate how a user can add co-authors and change the lead author.

### Tasks:
- [x] Create a video that shows how to add co-authors and change lead author.
- [x] Demonstrate the process of adding users (whatever their desired role) when they do not have an APT account.  
- [x] Upload video to this [folder](https://drive.google.com/drive/folders/1QYq75gh7RMKGi4tU1lnJBj9lx5paZ25e).
- [x] Submit the video to team for review.
- [x] Make edits based on feedback.
- [x] Share video link with DevSeed.
- [x] Determine location in UI
    - Required for https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/427

### **VIDEO**
[Help Video: Add Collaborators and Change the Lead Author](https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1)

### Acceptance Criteria
- [ ] Video is uploaded and working on PROD.

**Comment by bwbaker1** [comment]
Audio for this video is done.  We just need to add the screen recording - ~30 minutes.  Moving to sprint 5.
