### ISSUE TITLE
Help video: Submit and request ATBD review

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#618]
### Description: 
The process of requesting and submitting an ATBD for review could be slightly confusing for users.  Therefore, there is a need to explicitly demonstrate how this process works by giving users step-by-step instructions.  

### Tasks:
- [x] Create a video that shows the process of requesting and submitting an ATBD for review.
- [x] Upload video to this [folder](https://drive.google.com/drive/folders/1QYq75gh7RMKGi4tU1lnJBj9lx5paZ25e).
- [x] Submit the video to team for review.
- [x] Make edits based on feedback.
- [x] Share video link with DevSeed.

### Acceptance Criteria
- [x] Video is uploaded and working on PROD.

**Comment by bwbaker1** [comment]
This has yet to be started.  This should not take too long to complete.  I am moving it to sprint 5 for now, but it may need to be pushed to the next PI (depending on how much time we spend testing, etc.).

**Comment by bwbaker1** [comment]
This is discussion because we need to figure out what/how/if review will be.

**Comment by wrynearson** [comment]
@bwbaker1 this is in sprint 1. Should this be moved to another sprint?

**Comment by bwbaker1** [comment]
@ashleyriddle92 @cw0045 Is there an update on this? Does it need to be moved to S4?

**Comment by ashleyriddle92** [comment]
@bwbaker1 we're doing a video either today, if Camille's feeling up to it, or Tuesday.

**Comment by bwbaker1** [comment]
@wrynearson [Here](https://drive.google.com/drive/folders/1TcvjMS2emfLFmv0q5KirxVu9h-bp9ct1) is this video (transitioning the document between draft, review, and publication). I'm not sure where the best location is for this tooltip. Couple of suggestions:

1. Welcome to your document prompt
2. Near the "Request Review" and "Request Publication" buttons on the dashboard and within the document.

**Comment by kamicut** [comment]
@bwbaker1 @wrynearson should the video be public? I got an access denied message when clicking the above link.

**Comment by wrynearson** [comment]
@kamicut [here's the link](https://drive.google.com/file/d/1CmWvfC7JeUO-SGCvf7iOR6H4cMvS3vZX/view?usp=sharing) to the video itself. Brad had shared the link to the folder of all of the videos, which is private. I requested that you have access to that folder, which I think @bwbaker1 needs to approve.

**Comment by bwbaker1** [comment]
@kamicut @wrynearson I didn't receive an email for requesting access to the folder. However, I did add you Mar. Let me know if it didn't work.

**Comment by kamicut** [comment]
I was thinking we could add it as a secondary action in the "Welcome Document" or "Document Info" in the following way. Let me know what you think @bwbaker1 @wrynearson 

## welcome document

<img width="769" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/719357/9be29797-582e-4fba-9ca6-c9e09e7b3ec1">


## document info

<img width="769" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/719357/c63a54cc-a8de-4d13-bfa6-9d373e748c76">

**Comment by wrynearson** [comment]
Great idea @kamicut, I think it looks good there. @bwbaker1 this is ready for your review.

**Comment by bwbaker1** [comment]
@wrynearson @kamicut This looks good!
