### ISSUE TITLE
Fix bold and italics formatting across entire document

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#621]
@wrynearson @naomatheus 

### Description: 
_Split from https://github.com/NASA-IMPACT/nasa-apt/issues/601_

There is an issue of bold/italics formatting not rendering correctly (e.g., reference section).

### Tasks:
- [ ] ~Determine what is causing the bold/italics formatting issue~
- [x] Implement fix that resolves the bold/italics formatting issue (_fixed with #622_)

### Acceptance Criteria: 
- [x] PDFs display properly formatted text whenever bold and italics are used 
- [x] PDFs tested to ensure all bold/italics formatting displays correctly (need to check multiple sections/content types, references, etc.)

**Comment by bwbaker1** [comment]
@naomatheus  Feel free to revise this ticket if needed (especially if you know specifically were these formatting issues are occurring).

**Comment by wrynearson** [comment]
@naomatheus, FYI that @bwbaker1 split this ticket out from #601

**Comment by wrynearson** [comment]
This will be fixed once https://github.com/NASA-IMPACT/nasa-apt/pull/638 is merged and tested.

**Comment by wrynearson** [comment]
This is fixed. If you'd like, please review it (@bwbaker1 and @deborahUAH), otherwise we can safely close this ticket.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH @naomatheus This has been tested and looks good.
