### ISSUE TITLE
Epic: PDF related bugs/fixes

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#623]
### Description
There are many high priority issues relating to PDFs that need to be addressed.  Users need to be able to download their PDFs and these PDFs need to display all content and styled correctly.  It is also important to have a completed ATBD published which cannot happen until PDFs are downloadable and rendering correctly. 

### Tasks:
- [ ] All PDF bugs, content issues and styling issues are fixed and tested
- [ ] All PDFs are downloadable on PROD
- [ ] All PDF downloads render content and styling correctly

### Supporting Stories
- [x] #622 
- [x] #620 
- [x] #621 
- [x] #601 
- [x] #606 
- [x] #601 
- [x] #604 
- [x] #607 
- [x] #614 
- [x] #612 
- [x] #545
