### ISSUE TITLE
Help video: User login

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#624]
### Description
This help video will demonstrate how to log into APT.

### Tasks:
- [x] Create a video that shows how to login to APT.
- [x] Upload video to this [folder](https://drive.google.com/drive/folders/1QYq75gh7RMKGi4tU1lnJBj9lx5paZ25e).
- [x] Submit the video to team for review.
- [x] Make edits based on feedback.
- [x] Share video link with DevSeed.

### Acceptance Criteria
- [ ] Video is uploaded and working on PROD.

**Comment by bwbaker1** [comment]
Blocked until MFA is implemented.
