### ISSUE TITLE
Feature for contributors/reviewers to privately contact curator

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#626]
@wrynearson @deborahUAH 

### Description
Currently, users can use thread mentions to comment amongst each other - contributors, reviewers, and curators.  However, all users associated with a document can see all comments.  Some comments with the curator may need to be private and therefore not seen by everyone.  

### Tasks:
- [ ] Determine/discuss the best approach (simplest) way to allow users to privately interact with the curator (e.g., option for private comments within thread mentions - user selects who sees comments or perhaps an option to send email to the curator via a link)
- [ ] Implement approach that is decided on

### Acceptance Criteria:
- [ ] Users have a method to successfully interact with the curator privately (both contributors and reviewers need to be able to do this)

**Comment by wrynearson** [comment]
@deborahUAH could you give an example of when private communication would be helpful for the author/reviewer? In the spirit of openness (open source, open repository for ATBDs), I'd advocate for only having private communication if there's a compelling reason.

cc @batpad

**Comment by deborahUAH** [comment]
Conditions have changed and this will no longer be required.    Closing issue
