### ISSUE TITLE
Link for automated email to Curator when inviting new user to APT

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#627]
@wrynearson @deborahUAH This was discussed within IMPACT team (1/18) but needs a larger discussion in terms of feasibility. 

### Description
Currently, a user cannot add a contributor or reviewer to a document if the desired person does not have an APT account.  This could be confusing.  One solution is to have an email link (location TBD) that emails the desired person and CCs the curator and describes the process of signing up for an APT account.  The user making the request would input the desired person's name and email address and the email would be automatically sent to them.  Then they can be added to a document once they have an account.

### Tasks:
- [ ] Determine how challenging this feature would be to create/implement.
- [ ] Determine the best location for the entry of name and email of contributor
- [ ] Determine the content of the automated email (i.e., brief overview of APT, process of signing up, and who sent the invite and why)
- [ ] Implement the automated email

### Acceptance Criteria:
- [ ] APT provides name and email entry boxes that the document owner can use to invite someone to signup for APT and contribute to the document  
- [ ] This feature is tested and is working in production.

**Comment by deborahUAH** [comment]
Authors need to have a way to add authors.  Right now the lead author has to personally reach out via email the contributors they want to add to the document and ask them to get an account.  This should be made easier for lead authors.

This is a P1 priority development task for next quarter. FY23.3   @wrynearson

**Comment by wrynearson** [comment]
We can look into this to see how difficult it would be to implement.

One approach could be for users to be able to add emails (and maybe names) under the "Manage Collaborators" menu.

![Image](https://user-images.githubusercontent.com/25919630/220579133-774d19a3-44db-43d3-ba65-78f49e120e09.png)

If a user with the appropriate permissions (lead author? Any contributor?) adds a user to a doc, then that triggers the user to be created in Cognito. That user is sent an email inviting them to create a password, add their preferred username, and set up MFA.

We would need to think through the frontend design, how to indicate that a user's invite is pending/accepted/declined, and permissions around this.

This sort of approach makes more sense to me when we have a larger user base. If it's difficult to implement, is it worth implementing before handing off to ESDIS?

cc @batpad @sunu @frozenhelium

**Comment by wrynearson** [comment]
@bwbaker1 this is listed as a PI23.4 Milestone. Is this something we should prioritize?

**Comment by bwbaker1** [comment]
@wrynearson This was something that was discussed with Anthony during planning, but there are too many more important tasks ongoing. Closing as not planned.
