### ISSUE TITLE
Create APT ATBD template in Google Docs

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#629]
### Description:
ESDIS asked for an APT ATBD template using Google Docs, so that science teams can reference until APT is fully operational. 

### Tasks:
- [x] Create an ATBD template in Google Docs (base this on APT)
- [x] add short information blurbs describing each section
- [x] send template to Deborah for review

### Acceptance Criteria
- [x] Template is sent to ESDIS

**Comment by deborahUAH** [comment]
reviewed and sent to Cerese at end of sprint.  She forwarded templates to INCUS team.

**Comment by deborahUAH** [comment]
completed
