### ISSUE TITLE
Email notifications need to be directed toward specific curators

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#639]
### **Description**

Email notifications that are sent to curators are currently directed toward anyone having the curator role.  However, ESDIS has decided that each DAAC will host their own curator. This means that each curator will only be responsible for ATBDs associated with their specific DAAC.  Therefore, email notifications need to be directed toward specific curators.  For example, if a science team at the ASDC DAAC submit a review request for an ATBD, **ONLY** the curator(s) associated with the ASDC DAAC should receive this notification.   We want to ensure that curators are not being bombarded with unnecessary email notifications. 

Email notifications table #609. 

### **Tasks:**
- [ ] Review and determine what steps are needed to direct email notifications toward specific curator(s). Note: currently anyone assigned the curator role receives all notifications.
- [ ] Discuss the proposed solution with Impact team members.
- [ ] Implement the agreed upon solution.
- [ ] Test the implementation.
- [ ] After successful testing, let Impact know that this is ready for them to test.

### **Acceptance Criteria:**
- [ ] All email notifications are directed specifically toward curators at each DAAC.
- [ ] This has been tested (both DevSeed and IMPACT) and works as expected.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Please review this issue to make sure it makes sense.

**Comment by deborahUAH** [comment]
Just to clarify....    If authorized users can be associated with individual ATBDs, we need curators to also be associated with certain ATBDs.  That said, there will always be the need to provide all curators with general APT information also.

**Comment by wrynearson** [comment]
Thanks @bwbaker1 and @deborahUAH. I think this will be a pretty big change to the user permissions architecture if we are transitioning users with curator status from _all_ reports to _some_ reports. Frontend and backend changes will need to be made.

Several initial questions:
1. How will DAAC representatives be managed? Who will assign that person?
2. How will DAAC themes be set? What happens if these change?
3. How will ATBD authors select which theme/DAAC their ATBD belongs to? What happens if an ATBD needs to change themes/DAACs?

**Comment by wrynearson** [comment]
I'm also curious why this is a P1 priority and is listed in this PI (FY23.2)?

cc: @batpad @thenav56

**Comment by bwbaker1** [comment]
@deborahUAH Should we close this or move it to the backlog?

**Comment by deborahUAH** [comment]
hmm.   I think we can move to backlog.  If it is decided that APT will continue to be used, then this will be a needed feature since there will be different DAAC curators and communication would be more efficient if directed to the assigned curator for the ATBD.  @bwbaker1 thoughts?

**Comment by bwbaker1** [comment]
agreed. moving to backlog.
