### ISSUE TITLE
Add Curator Guide into APT

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#648]
### **Description**
The curator guide is now complete and needs to be made available on the APT.  This guide will only be visible to users' having a curator role. 

[Document](https://docs.google.com/document/d/1TB0Yy8_QqrO9zDvcgIJODLxLnpHH5TR3mKlp4OHhyUk/edit#)

### **Tasks:**
- [ ] Place the curator guide onto the APT. 

### **Acceptance Criteria:**
- [ ] Curator Guide made available on the APT for curator view only
- [ ] Team member test to ensure the curator guide is located on the APT in the right location and that the content is correct.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH

**Comment by bwbaker1** [comment]
@wrynearson @frozenhelium @deborahUAH Closing this issue.  It was decided that we will just hand the curator guide over to the curators instead of having it available within APT.
