### ISSUE TITLE
User's should not be able to edit other users thread comments

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#656]
### **Description**
Currently, a user associated with a document can edit any comments within that document. For example, contributor 1 leaves a comment, then contributor 2 can edit that comment.  The comment thread notes that the comment was edited, but it does show the original comment. This is an undesirable feature.  Only the originator of the comment should be able to edit it.

### **Tasks:**
- [x] Remove the ability of users to edit other user's comments.
- [x] If possible, keep the ability of a user to edit their own comment.

### **Acceptance Criteria**
- [x] Comment thread updated so that a user can only edit their own comments.
- [x] The update is thoroughly tested and working as expected.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH

**Comment by wrynearson** [comment]
Hi @bwbaker1, we looked into this ticket. Right now, only the owner of a comment (i.e., the person who wrote it) and `curators` can edit comments. This ticket says that two contributors can edit each other's comments. Could you confirm that this is the behavior you saw?

Here's what I tested 🎥 :

https://user-images.githubusercontent.com/25919630/228146239-664dd9ce-1f75-4cc9-ab14-66db34536c37.mov

The way it is coded makes us think that this is the desired functionality. Could you and @deborahUAH please let us know if it's _not_ the desired behavior?

cc @thenav56

**Comment by deborahUAH** [comment]
@wrynearson I do not recall any discussion regarding comment editing (could have happened before I became involved with APT? - I can try to find out).  To me - the only reason I think the curator should be able to edit an authors comment is if it is inappropriate in some way.  But even then, I don't think it is right for the curator to do that.    I suggest that no one should be able to change another user's comment.  Can you think of any reason to do so?

**Comment by wrynearson** [comment]
@deborahUAH the rationale I heard from previous APT team members was that the curator role is like an administrator, which would let them manage the platform. The reason you said seems like the only reason I can think of. In this scenario (if someone leaves an inappropriate comment), what would your preferred action be?

We can change the ability for curators to edit comments quite easily.

cc @bwbaker1 @thenav56 @batpad

**Comment by wrynearson** [comment]
@thenav56 could you go ahead and change the permissions so that curators cannot edit other people's threads / comments?

**Comment by bwbaker1** [comment]
@wrynearson I tested this and it is working correctly.  I am only able to edit my own comments. This is ready for production.

**Comment by wrynearson** [comment]
Merged to production with https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/462
