### ISSUE TITLE
Epic: Automated testing for APT

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#659]
## Description

Currently APT doesn't have any tests either for the backend or the frontend. We should aim to have some test coverage especially for parts that are prone to regression and bugs (eg: reference formatting, PDF formatting, API permissions) and then gradually aim to improve our test coverage.

IMO, it would be good to start by writing unit tests for things that are easy to test in isolation and some end to end tests that test the view mode output and exported PDFs visually or structurally for expected content.

I suspect our dependence on things like localstack cognito is going to make it complicated and slow to run end-to-end tests on the CI though.

## Tasks

- [x] #668
- [x] Unit tests for things are easy to test in isolation
- [x] API tests to catch permission issues or change in interface
- [x] End-to-end tests for view mode content and PDF export

**Comment by bwbaker1** [comment]
@kamicut @sunu Is this ticket completed? If so, can we close out the ticket?
