### ISSUE TITLE
Update Latex user guide

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#672]
### Description: 
Update all training materials with new figures and text so users have accurate support materials

[LaTex Help](https://docs.google.com/document/d/1O90EhaMJAaEtNsnAng3xZvD4S_mxEOJ6WOycBuRuyRc/edit#heading=h.5dxey8lopcao)

[User guide imagers](https://drive.google.com/drive/folders/1CQN1dH5x3zMKzEKR5xAgQFc2AsljzD7n)

### Tasks:
- [x] Be sure to include inline and block features
- [x] Polish text and make sure it is user friendly (Camille)
- [x] Update all figures
- [x] Update figure images on Github
- [x] Update markdown file

### Acceptance Criteria:
- [x] Updated latex user guide completed and available on the APT

**Comment by bwbaker1** [comment]
@deborahUAH FYI in case you want to review this. Camille is working on reviewing/editing now. This guide was ~2 years out-of-date, so all of the figures are new.

**Comment by bwbaker1** [comment]
@wrynearson The latex user guide is ready for production. Let me know if you need me to update the markdown file.

[Figure images](https://drive.google.com/drive/folders/1CQN1dH5x3zMKzEKR5xAgQFc2AsljzD7n)
[Latex user guide](https://docs.google.com/document/d/1O90EhaMJAaEtNsnAng3xZvD4S_mxEOJ6WOycBuRuyRc/edit#)

**Comment by wrynearson** [comment]
@bwbaker1 yes, if you would have time to update the markdown file, that would be fantastic.

The file is [here](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/0202fc872d17da880e8da699e838307c2bc292fb/content/help-documentation/latex.md). Feel free to send or post the updated Markdown file here and I can add it to staging. If you have any issues, please let me know.

**Comment by bwbaker1** [comment]
@wrynearson This [file](https://github.dev/NASA-IMPACT/nasa-apt-frontend/blob/0202fc872d17da880e8da699e838307c2bc292fb/content/help-documentation/latex.md) is updated and ready for staging.

**Comment by wrynearson** [comment]
Sorry @bwbaker1, I'm not able to see your updates to the file. Could you create a new branch, commit the changes (if you edited the file directly in the github.dev codespace), and open a PR?

If not, no problem – feel free to email me the .md file and I can get it on staging 😄
