### ISSUE TITLE
Create Latex template

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#673]
### **Description**
As we proceed with giving users the option to use templates or the APT UI, we need to provide multiple template options.  We currently have a Word and Google Doc template, but we also need a Latex template. This template should match the previous templates.

[APT Latex Template.zip](https://github.com/NASA-IMPACT/nasa-apt/files/11336002/APT.Latex.Template.zip)

### Tasks:
- [x] Use the existing templates to create a Latex template.
- [x] Ensure users can add content to the template.
- [x] Add instructions to the document.
- [x] Test generating a PDF using the template (make sure it is correct).
- [x] Add text document with instructions.

### Acceptance Criteria: 
- [x] We have a working Latex template
- [x] Template is delivered to DevSeed to place on the UI

**Comment by wrynearson** [comment]
> Template is delivered to DevSeed to place on the UI

@bwbaker1 could you explain what you mean here?

**Comment by bwbaker1** [comment]
@wrynearson This just means that users will be able to access/download the templates from APT. This is my understanding of the desired outcome, but we can all discuss next week.

**Comment by bwbaker1** [comment]
@deborahUAH @cw0045 Latex template is done. Please review it when you have a chance and make sure it looks correct.

**Comment by bwbaker1** [comment]
@wrynearson [Here](https://drive.google.com/drive/folders/1fwa9vLmz4QaU2e8CG9JscgXmEHp7J8mM) is the folder with the latex template. All 5 files in the folder are needed. This is ready to go.

**Comment by wrynearson** [comment]
@bwbaker1 I've added the three templates as Google Drive links to make storage and updating simple (https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/474/commits/530b885b668304327f151fdd63f66e81aea89fa4):
1. LaTeX – I zipped the 5 files in the folder ☝️, added the .zip to the same parent folder, and made that file publicly viewable with the link
2. Word – I changed the view permissions of the file in the same parent folder to viewable with the link
3. Google Docs – I changed the view permissions of the file in the same parent folder to viewable with the link

If you want to change any of the files (updates, etc.), you can right click on the file and click "Manage versions". This will keep the link the same

<img width="1127" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/9fd2f5db-c3ee-478d-8f9b-aa3ab647fabc">
