### ISSUE TITLE
Help Video: How to use templates

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#674]
**### Description**
Users selecting the template option will need clear instructions how to handle/submit their template. A short help video demonstrating this process will be helpful.

What needs to be shown.
1. Download a template
2. After logged in, "create a new document"
3. Select to submit existing ATBD PDF
4. Go through the steps and upload PDF
5. Show viewing mode 

### Tasks:
- [x] Determine what the submission process will look like
- [x] Create a video demonstrating the process
- [x] Send video to team for review/make suggested edits
- [x] Upload completed video to Drive
- [x] Determine where the video should be placed on APT

### Acceptance Criteria:
- [x] Help video placed on Drive
- [ ] DevSeed places video on APT

**Comment by bwbaker1** [comment]
@wrynearson Here is the link to this [video](https://drive.google.com/file/d/16MuIDDlXtnDFBpfY6pJbHjjJS3KrzBnQ/view?usp=drive_link).  I think we should link it in two places, but we can discuss at our meeting on June 21.

1. I think we should add the link on the Create new ATBD page (see [this](https://docs.google.com/presentation/d/1z0GKsChxL5OnQb1qUy2aYQxkVllZ_BT9ml7zoim20B8/edit#slide=id.g253cf7f73c3_0_0)).

2. And link it here. 


![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/78d40cb5-c139-4545-8e0a-dd2cfedd2e3f)

**Comment by wrynearson** [comment]
Hey @bwbaker1, I've added the video to the tooltip pictured above. Is there another location that the video should also be mentioned?

<img width="801" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/df195a28-e9a9-4ea9-b575-80565e107e9f">

The video requires users to sign in to view it. Could you change the video's permissions to allow anyone with the link to view it?

I've also updated the text on the comparison page to link to the quick start guide.

<img width="636" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/6e1906a6-e0b9-408e-9b4e-a4d01d91e948">


Please let me know if I'm missing anything.

**Comment by bwbaker1** [comment]
@wrynearson Thanks!

1. I changed the permissions on the video (good catch).
2. I like the video link on the tooltip.
3. The updated text/link for the quick start guide looks good on the comparison page.
4. I was thinking we could also add the video link on the comparison page as well.... maybe "See the Quick Start guide or watch this video for more information." Do you think this is too much or is bad web design?

**Comment by wrynearson** [comment]
Thanks @bwbaker1, I've added it like this:

<img width="626" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/fa7e0333-79f4-4e13-b1f7-30767cd6b0c1">

I think it's a good idea, I just didn't understand where the second link to the video should go 😄. We can always improve it in the future.

**Comment by wrynearson** [comment]
I guess having a video frame in the left column, but a link in the right column is inconsistent, but from a design perspective I think it doesn't overwhelm users which is good.

**Comment by bwbaker1** [comment]
@wrynearson Awesome. Will you remove the first "for more information"? So it would be "See the Quick Start guide or watch this video for more information."

A few of us discussed the inconsistency of having a video frame and a link, but we thought that it would be overwhelming to have two video frames along with the template downloads.

**Comment by wrynearson** [comment]
Done, this will be on staging once someone reviews the PR.

<img width="591" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/b8ccfd2f-8186-431f-8654-f8f7ba008b53">
