### ISSUE TITLE
Create content for new APT page "Create a new ATBD"

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#675]
### **Description**
APT needs a new page "Create a new ATBD" (name TBD) that describes the user's choice of authoring an ATBD (template or APT environment) and how to get an account.

[Draft Design](https://docs.google.com/presentation/d/1z0GKsChxL5OnQb1qUy2aYQxkVllZ_BT9ml7zoim20B8/edit#slide=id.p)

### Tasks:
- [x] Describe users options of template or APT environment
- [x] Text explaining you must have an account to upload an ATBD PDF
- [x] Team discussion/design of new page (i.e., where will templates be placed, will it be drop down, etc.)
- [x] Link (button) directing users to sign-up page
- [x] Have team review final draft
- [ ] Submit to DevSeed for implementation

### Acceptance Criteria:
- [ ] New  page draft/design submitted to DevSeed

**Comment by bwbaker1** [comment]
@wrynearson [Here](https://docs.google.com/presentation/d/1z0GKsChxL5OnQb1qUy2aYQxkVllZ_BT9ml7zoim20B8/edit#slide=id.p) is our general idea of what this page should contain and how it should look.
