### ISSUE TITLE
Number Tables and place captions above table

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#681]
**### Description**
There is a need to polish document tables to better fit with standard AGU/APA practices.

### Tasks:
- [ ] Tables need to be consecutively numbered in chronological order. The format should match figure numbers.
- [ ] The table caption should be placed on top of the table. (see example below)

### Acceptance Criteria: 
- [ ] Tables are consecutively and chronologically numbered
- [ ] Table captions appear at the top of tables
- [ ] PDFs are to ensure tables are numbered and captioned properly.

![Image](https://user-images.githubusercontent.com/56319064/230419493-4bd3ed51-c85a-4fc4-a35a-5f42380d0c41.png)

**Comment by wrynearson** [comment]
@bwbaker1 are you requesting this for the view mode or just the Document and Journal PDFs?

**Comment by bwbaker1** [comment]
@wrynearson Just both PDFs.  If this is a relatively easy fix, great, otherwise it's not a high priority at the moment.

**Comment by bwbaker1** [comment]
@wrynearson What is the LOE to add figure, table, and equation numbers to both view mode and PDFs? This is coming from user feedback.

**Comment by wrynearson** [comment]
Sorry I missed this @bwbaker1. Adding to the PDFs will be low LOE (we already have them for figures and equations) but more complex to add things back into the view mode. @frozenhelium, please correct me if I'm wrong.

**Comment by bwbaker1** [comment]
No worries @wrynearson. I want this issue (adding just to PDFs) to be our next priority following the PDF upload, as long as it is rather simple and fast to implement. 
For Q4 planning, I would like to get a good estimate of the LOE to add all of these numberings to the view mode. This would be a good addition to better the user experience, so it's worth looking into. It's already on our planning document.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This looks good. However, images and equations are no longer numbered on the document PDF. See below. These are still numbered on the journal PDFs. 

Document PDF
![Screen Shot 2023-10-04 at 8 52 40 AM](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/1b452656-e1f7-4475-891e-d2d79088e9c6)

Journal PDF
![Screen Shot 2023-10-04 at 8 53 42 AM](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/5272215a-9edc-4021-ae81-7a71b1612656)

**Comment by bwbaker1** [comment]
@wrynearson The document PDF still isn't generating correctly. See [comment](https://github.com/NASA-IMPACT/nasa-apt/issues/681#issuecomment-1746929215). Figures and equations are no longer numbered. And the table captions should be above the table (this is correct on the journal PDF).

**Comment by wrynearson** [comment]
@bwbaker1 could you try changing the document in some way and then trying again? @kamicut @sunu any ideas besides that Brad is accessing a cached version of the PDF?

**Comment by bwbaker1** [comment]
@wrynearson I've made changes and tested a few times. Sometimes the table captions appear above the table and sometime they don't. Figures and equations are still missing numbers every time I've tested. Here is the document I am testing: https://www.earthdata.nasa.gov/apt/documents/journal-pdf-testing/v1.0

**Comment by bwbaker1** [comment]
@wrynearson I also noticed the document title is no longer centered on the document PDF (it is on the journal PDF).

**Comment by vgeorge** [comment]
Table and image numbering in PDFs should now be functional on staging. However, there's a pending issue with equations number in the journal PDF, which I'm currently investigating. They are not incrementing.

**Comment by bwbaker1** [comment]
@vgeorge I'm seeing the incremental issue with the equations on the journal PDF.
The document PDF looks good with one exception. The figure captions should be placed below the image. Table and equations look good on the document PDF.

cc @wrynearson

**Comment by wrynearson** [comment]
Hi @bwbaker1, both of these issues (incremental equation numbering and figure caption location) will be ready for your review on staging in about 15 minutes.

**Comment by bwbaker1** [comment]
@wrynearson Fantastic! I was about to ask about them.

**Comment by bwbaker1** [comment]
@wrynearson This looks good to me. It's ready for production.

**Comment by wrynearson** [comment]
@sunu can you add this to the production deployment?

**Comment by sunu** [comment]
> @sunu can you add this to the production deployment?

@wrynearson will do!

**Comment by bwbaker1** [comment]
@wrynearson I believe we can close this ticket since it works correctly for both PDFs on production.
