### ISSUE TITLE
Add "Discussion" section from "Journal Details" to the general PDF

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#682]
### **Description**
After some review, we have determined that the "Significance Discussion" section from the "Journal details" must be included on the general PDF. The significance discussion section is optional for users not going the journal route, however, this section must be included for ATBDs that do have this section. 

### Tasks:
- [x] Add the "Discussion" section from the Journal Details to the general PDF (should also remain on Journal PDF)
- [x] Ensure that the general PDF is ordered/numbered correctly (see example below)
- [x] Test the PDF download

### Acceptance Criteria:
- [x] general PDF includes the Discussion section
- [x] download thoroughly reviewed/tested

Example: 

![Image](https://user-images.githubusercontent.com/56319064/230668871-9478698c-30ee-4814-b2f5-f7e435e7b910.png)

**Comment by wrynearson** [comment]
Hey @frozenhelium, could you take on this ticket when you have the chance? If you have any questions or need more context, please let me know

**Comment by bwbaker1** [comment]
@wrynearson @frozenhelium Is this issue being worked on or did it get deprioritized?

**Comment by wrynearson** [comment]
@bwbaker1 this was deprioritized. If you want us to prioritize it, we can add it into the next sprint. cc @frozenhelium

**Comment by bwbaker1** [comment]
@wrynearson What is the estimated LOE for this and how much would it take away from the new user workflow priorities?

**Comment by wrynearson** [comment]
@frozenhelium @batpad let's estimate this ticket next week. I don't think it'd be more than half a sprint, but I'd want to hear from the team first.

**Comment by frozenhelium** [comment]
In code level, Journal detail section is implemented slightly differently than all other section. So, the section / heading hierarchy is slightly different. This affects how the PDF section renders ToC (This issue was captured previously as well but was left as to be fixed later, since we decided to hide the section). 
We should refactor the section to follow the pattern, so it'd take a bit more time to implement.

**Comment by wrynearson** [comment]
Thanks @frozenhelium. @bwbaker1, @frozenhelium will be focusing on https://github.com/NASA-IMPACT/nasa-apt/issues/690 and https://github.com/NASA-IMPACT/nasa-apt/issues/708 this sprint, so we won't have capacity to work on this ticket this sprint. I will put it in for next sprint, but we may have to adjust it depending on requirements for https://github.com/NASA-IMPACT/nasa-apt/issues/714

**Comment by bwbaker1** [comment]
@wrynearson We will need to implement this at some point, but let's hold off for now. I reviewed all of the ATBDs that are currently being worked on within the interface, and none of them are including the discussion section. But it's good that this was scoped out (thanks @frozenhelium). 

Once the PDF upload is implemented, I can use it as a workaround to add our Demo ATBD, which does have discussion section, to the repo.

**Comment by frozenhelium** [comment]
@wrynearson Should we also change the order of  `Reference` and `Journal Details` in view mode? Right now pdf export relies on the view mode. So, it'd be easier if they had same order.

**Comment by wrynearson** [comment]
@frozenhelium do you mean the `Discussion` section from the Journal Details? Let's see what @bwbaker1 thinks first, but yes, I think the view and PDF should have the same order.

**Comment by frozenhelium** [comment]
I mean, in the view mode, **Journal Details** section will appear before the **Reference** which will make the **Significance Discussion** appear before **Reference** in the pdf (As shown in the ToC screenshot above)

## In view mode

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/4931541/5168e873-5ef4-4313-a752-b49420a64a08)

## In pdf mode

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/4931541/0faa6ecd-2594-4373-b40a-004d0ce9c097)

**Comment by wrynearson** [comment]
Yes @frozenhelium, I think it's OK to have the view mode match the PDF. Let me know if you disagree @bwbaker1

**Comment by bwbaker1** [comment]
@wrynearson ⬆️ That is fine. It's makes more sense to me if view mode and the PDF match.

**Comment by wrynearson** [comment]
OK great, this will be on staging in ~15 minutes

**Comment by bwbaker1** [comment]
@wrynearson This looks good except for the section order. And sorry I didn't catch this yesterday. "Significance Discussion" should come before "Contacts." See below.

7. Algorithm Implementation
8. Significance Discussion
9. Contacts
References

**Comment by wrynearson** [comment]
cc @frozenhelium – let me know if this complicates anything.
