### ISSUE TITLE
General PDF re-order/rename section headers to match journal PDF

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#683]
### **Description**
A few section headings on the general PDF need to be reordered and renamed to match with the Journal PDF. 

### Tasks: 
- [ ] Section "Algorithm Availability" needs to move within Data Access
- [ ] Performance Assessment subheadings need renaming (remove "Performance Assessment").  The top level header remain as "Performance Assessment Validation."
- [ ] Data Access subheadings need renaming. "Input Data Data Access" becomes "Input Data Access" and "Output Data Data Access" becomes "Output Data Access."
- [ ] Remove section number from "References."

See below example for how it needs to look.

### Acceptance Criteria:
- [ ] General PDF is reordered/renamed to match example.
- [ ] PDF downloaded and reviewed to make sure it is the correct order.

![Image](https://user-images.githubusercontent.com/56319064/230670343-b27a5d7a-2b10-4843-a211-bc8ff49d8c06.png)

**Comment by wrynearson** [comment]
Hi @bwbaker1, we're assuming that these need to be changed in the view mode?

> Section "Algorithm Availability" needs to move within Data Access
Could you explain why the heading structure needs to change?

**Comment by bwbaker1** [comment]
@wrynearson This ticket is not a priority.  I'm closing it.

**Comment by wrynearson** [comment]
I'll mark it as the other type of closed to indicate that this work wasn't done.
