### ISSUE TITLE
Create Word Doc template

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#684]
### **Description**
As we proceed with giving users the option to use templates or the APT UI, we need to provide multiple template options.  We currently have a Google Doc template, but we also need a Word template. This template should match the previous templates.

### Tasks:
- [ ] Use the existing templates to create a Word template.
- [ ] Ensure users can add content to the template.
- [ ] Add instructions to the document.
- [ ] Test generating a PDF using the template (make sure it is correct).

### Acceptance Criteria: 
- [ ] We have a working Word template
- [ ] Template is delivered to DevSeed to place on the UI
