### ISSUE TITLE
Update APT About page

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#689]
### **Description**
APT's About page needs to be reviewed and potentially updated to reflect the new user workflow (i.e., template vs APT environment).

### **Tasks**
- [ ] Review current About page
- [ ] Document any needed changes
- [ ] Submit to DevSeed for implementation

### **Acceptance Criteria**
- [ ] About page updated on production

**Comment by bwbaker1** [comment]
Closing as not planned. We do not think anything on this page needs updating at the time.
