### ISSUE TITLE
Update APT welcome page

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#690]
## **Description**
As part of APT's new user workflow, we need to update the Welcome page to direct users to a new page.

## **Tasks**
- [ ] Change the name of the button "Explore the documents" to "Explore existing documents"
- [ ] Add a new button beside the button "Explore the documents" with the text "Create a new ATBD"
- [ ] This new button should direct users to a new page (page name TBD)

### **Acceptance Criteria**
- [ ] Name of existing button is updated to "Explore existing documents"
- [ ] New button "Create a new ATBD" is added
- [ ] New button directs users to new page
- [ ] These new additions are thoroughly tested

Draft Example

![Image](https://user-images.githubusercontent.com/56319064/232495994-ecd8303d-2d45-4447-89e3-c6780c9f9a6e.png)

**Comment by bwbaker1** [comment]
@wrynearson

**Comment by wrynearson** [comment]
@bwbaker1 we're working with our design team to come up with a unified strategy, so depending on their delivery of the designs (probably late next week), we might have to push this ticket to the next sprint.

**Comment by wrynearson** [comment]
Update @bwbaker1 we have a few design options from our design team. I will work with our developers tomorrow and will walk through what we're thinking during our scheduled call for May 2nd. Development can start ASAP after we are on the same page

**Comment by wrynearson** [comment]
See https://github.com/NASA-IMPACT/nasa-apt/issues/714#issuecomment-1531677802 for a status update.

@batpad @frozenhelium / @kamicut, we should prioritize updating the APT welcome page to inform users that they can download APT templates. I will scope this out tomorrow.

**Comment by wrynearson** [comment]
@bwbaker1 What are your thoughts about using the `Learn more` [page](https://github.com/NASA-IMPACT/nasa-apt/issues/675) instead of creating a new page with https://github.com/NASA-IMPACT/nasa-apt/issues/675?

**Comment by bwbaker1** [comment]
@wrynearson 

- I think this could work. I think we still need the content from [here](https://docs.google.com/presentation/d/1z0GKsChxL5OnQb1qUy2aYQxkVllZ_BT9ml7zoim20B8/edit#slide=id.p) (content in red box) on the page. It doesn't have to be designed the way we have it on the slide, we can change it to make it have a logical flow.

- We would need to change the text on the "Learn more" button to "Learn more to get started" or something similar.

- I think this approach would be better. The fewer the webpages the better. I just want to make sure we don't clutter the page too much.

**Comment by wrynearson** [comment]
Thanks @bwbaker1, agreed on the logic and motivations. This also give us the chance to update the site in the future without having to create additional pages. We'll use the content from the red box. cc @frozenhelium

**Comment by wrynearson** [comment]
@bwbaker1 here's the homepage and new ATBD create page that we have. It's not yet on staging because we thought we'd wait until we have all of the content and links sorted.

https://user-images.githubusercontent.com/25919630/236826904-48a50bf3-be37-4f1b-9345-10b4e78abca3.mov

**Comment by wrynearson** [comment]
@bwbaker1 based on your team's comments yesterday, here's the updated new page:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25919630/237015838-7720d5b3-fab7-48e5-83da-bbc942edaa16.png">

**Comment by bwbaker1** [comment]
@wrynearson We all agreed this looks good! Thanks!
