### ISSUE TITLE
Create a template user guide

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#691]
## **Description**
APT users that decide to use the template option will need a guide to describe the process of using the template (e.g., how to download/complete, get an account, review, and upload to APT).

[Draft](https://docs.google.com/document/d/1V9l6CU39PGNQ8KtfFZ2apFTlkHU04TGiFlFUhgkjYP0/edit)
## **Tasks**
- [ ] draft template user guide
- [ ] submit to team for review/edits
- [ ] make edits
- [ ] submit to DevSeed for implementation into the interface (with other user guides)

## **Acceptance Criteria**
- [ ] completed template user guide is published to the APT interface
