### ISSUE TITLE
Template PDF upload submission form (impact)

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#692]
## **Description**
There needs to be a form that users use to upload their ATBD PDFs. 

Draft form [here](https://docs.google.com/forms/d/18c1nwqEZgaacd_yx24QnJI4uNevUfbDCurKDt5uhkF4/edit). Created using Google Form, but this is only a reference template. No decision has been made if we will use Google Forms.

Related to #707 

## **Tasks**
- [x] Determine what questions need to be on the form (see image below)
- [ ] Build template form
- [ ] Impact to review form questions

## **Acceptance Criteria**
- [ ] Template form is submitted to DevSeed for implementation

![Image](https://user-images.githubusercontent.com/56319064/231582885-8eae2bc6-b6c9-4232-915a-2a04087f2ecd.png)

**Comment by bwbaker1** [comment]
@ashleyriddle92 Please review and edit this [draft form](https://docs.google.com/forms/d/18c1nwqEZgaacd_yx24QnJI4uNevUfbDCurKDt5uhkF4/edit). 
I just brain dumped content into bullets, so this needs a major re-working/polishing so that it flows and makes sense. The question fields also need review. Please prioritize this over your other APT tasks.

**Comment by bwbaker1** [comment]
@deborahUAH Please review this [draft](https://docs.google.com/forms/d/18c1nwqEZgaacd_yx24QnJI4uNevUfbDCurKDt5uhkF4/edit) when you have time. FYI, I not sure if it is possible to add a table in Google Forms (for author and reviewer info), but we can figure that part out later.

**Comment by wrynearson** [comment]
@bwbaker1 is this ticket related to the full implementation of the form or just the fields on your side? If it's the former, we won't have it ready this sprint.

> Enter the name of instrument used to measure or record data related to your algorithm.

Is this somewhere in the current APT ATBD creation flow?

> For each author/contributor on this ATBD, list the author's first and last name, [CRediT role](https://credit.niso.org/), [ORCID](https://orcid.org/), and affiliation.

I think including a field like this would be problematic for metadata storage, but we can investigate later.

For [these](https://docs.google.com/forms/d/18c1nwqEZgaacd_yx24QnJI4uNevUfbDCurKDt5uhkF4/edit) questions, which ones are you expecting to have search / potential filters run on? If the content is already in the PDF and we won't need to display/search/filter on a particular field, I would suggest not including it as it will make it easier for the user.

For example, in the current public document view, we only have the title, author, year, version, and abstract sections visible in the preview:

![Image](https://user-images.githubusercontent.com/25919630/233671359-0275f41c-fdf6-4bbf-bc03-2cc1316952f6.png)

**Comment by bwbaker1** [comment]
@wrynearson 

1. I will separate this into two tickets - (1) form questions/template and (2) implementation. 
2. I was curious if it would be possible to add a metadata field with authors, orcid, etc. We can discuss this next week (4/25)
3. Not all of the questions on the form are related to search. We would like to have some of this info. I think its okay as long as the form takes 5-10 minutes to complete. We can discuss this further though.

**Comment by bwbaker1** [comment]
Form not needed - Metadata collected through APT interface.
