### ISSUE TITLE
Update sign-up form

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#694]
## **Description**
APT would like to know a little more information about new users, such as why they are requesting an account.

## **Tasks:**
- [ ] Determine what extra information we would like to ask
- [ ] Submit updated content to DevSeed for implementation

## **Acceptance Criteria:**
- [ ] Content of sign up form is updated on production
- [ ] Sign up form is thoroughly tested
