### ISSUE TITLE
User documents not downloading on PROD

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#696]
## **Description**
Two users have reached out because they are having issues downloading their PDFs (https://www.earthdata.nasa.gov/apt/documents/opera-dist-product-atbd/v1.0 and https://www.earthdata.nasa.gov/apt/documents/tempo-nitrogen-dioxide/v1.0). 

Note: can add "/pdf-preview" to the end of the URL as a workaround for now.

## **Tasks:**
- [ ] Determine why these are not downloading
- [ ] Determine and implement a solution (note, if this a pdf generation timing out issue, it will be addressed with [#451](https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/451#:~:text=PDF%20generation%20before-,user,-is%20warned%20the))

## **Acceptance Criteria**
- [ ] PDFs are downloadable
- [ ] Notify users

**Comment by bwbaker1** [comment]
@wrynearson Created this ticket for tracking purposes.  You noted that you were able to download this [one](https://www.earthdata.nasa.gov/apt/documents/opera-dist-product-atbd/v1.0 ), but I still can't. Not sure what the issue is.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. I just retried the first one, but I'm also not able to downloaded it. I must have been mistaken

**Comment by wrynearson** [comment]
cc @batpad @sunu @naomatheus

**Comment by bwbaker1** [comment]
@wrynearson There are two versions of that document and both are named exactly the same.  One will download, but it's not the document that they are actively working on.  Not sure why they created two.

**Comment by naomatheus** [comment]
I believe we're ready for review on this. RE #701 
cc @wrynearson @sunu

**Comment by wrynearson** [comment]
Hi @bwbaker1, this push to production fixed the [Tempo](https://www.earthdata.nasa.gov/apt/documents/tempo-nitrogen-dioxide/v1.0) doc, but we are still having issues with the [OPERA](https://www.earthdata.nasa.gov/apt/documents/opera-dist-product-atbd/v1.0) document. We'll need to do more investigation with @naomatheus since the error logs are within MCP. 

cc @sunu

**Comment by bwbaker1** [comment]
^ I noticed that when testing yesterday. The good news is that the other documents I tested all downloaded very smoothly.

**Comment by sunu** [comment]
We have identified [the issue](https://github.com/NASA-IMPACT/nasa-apt/issues/704) that's causing the [OPERA](https://www.earthdata.nasa.gov/apt/documents/opera-dist-product-atbd/v1.0) document export to fail and we're working on a fix

**Comment by wrynearson** [comment]
Closing this, continuing with https://github.com/NASA-IMPACT/nasa-apt/issues/704
