### ISSUE TITLE
Add "Create a new ATBD" webpage

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#708]
### **Description**
APT needs a new page "Create a new ATBD" (name TBD) that describes the user's choice of authoring an ATBD (template or APT environment) and how to get an account.

Impact will send template with content TBD.

### **Tasks:**
- [ ] Implement new page "Create a new ATBD"
- [ ] Content/Design TBD

### **Acceptance Criteria:**
- [ ] New page on production
