### ISSUE TITLE
Contact marked as corresponding author should be the first contact listed on document

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#709]
### **Description**
Currently, contacts appear on the ATBD in the order that the author adds them. This is good, but it could be better if the corresponding author is automatically listed first. 

### **Tasks:**
- [x] Determine how to automatically list the corresponding author first in the Contacts section
- [x] Implement so the corresponding author is automatically first

### **Acceptance Criteria**
- [x] Corresponding author placement is implement on production
- [x] Corresponding author placement is thoroughly tested

**Comment by bwbaker1** [comment]
@wrynearson This came from user feedback but is not a priority. It may be worthwhile to think about next PI.

**Comment by kamicut** [comment]
This ticket is being handled as part of https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/559

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging (for view and document PDFs only – we weren't sure if it also applied to the journal PDF)

**Comment by bwbaker1** [comment]
@wrynearson Yes, this should appear on both the general and journal PDFs. This looks good for the document PDF. Thanks for taking care of this task, I didn't think it would happen this quarter!!

**Comment by wrynearson** [comment]
No problem! What's the sort order after the `corresponding author`? Just the order that the user added the contacts in?

**Comment by bwbaker1** [comment]
@wrynearson Just saw the previous comment. The remaining contacts should be listed in the order that they were added. Users should be listing the contacts in the order in terms of how much the author attributed to the document. 

This seems to be working as expected, so we can probably close this ticket.
