### ISSUE TITLE
Epic: ATBD PDF Upload

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#714]
For NASA FY23Q3, a new feature is requested to allow for uploading ADBD PDFs into APT, allowing users to use other editing tools (Word, Google Docs, and LaTeX) or to upload historical ATBDs. A new workflow, infrastructure, and document search/display capabilities will need to be added.

```[tasklist]
### Components
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/725
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/726
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/727
```

To inform users of the changes that are coming, and to let them start on the template-based ATBD creation workflow, we have a few tasks for this sprint
```[tasklist]
### Tasks for Sprint 2
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/473
```

**Comment by wrynearson** [comment]
Update from call with @bwbaker1, @deborahUAH  and APT team:
- @wrynearson shared [Miro board](https://miro.com/app/board/uXjVMT8wVqY=/) of design options
- All agreed that option A (more integration of the PDF upload functionality) is better than option B (having users submit a separate form
- @bwbaker and @deborahUAH stressed that there's pressure from IMPACT to show visible progress, and to allow users to start using templates ASAP
    - DevSeed will prioritize https://github.com/NASA-IMPACT/nasa-apt/issues/690

## Actions
- [x] DevSeed to get templates on home page, then we can reveal them later in the workflow at a later stage
- [x] DevSeed to add text to explain the template options, pros and cons
- [x] https://github.com/NASA-IMPACT/nasa-apt/issues/690
- [x] https://github.com/NASA-IMPACT/nasa-apt/issues/675

cc @batpad @frozenhelium

**Comment by bwbaker1** [comment]
@wrynearson also note 
- #675
