### ISSUE TITLE
Submit abstract for MSFC Jamboree

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#716]
### **Description**
MSFC is having annual post jamboree June 22. In order to have a poster, an abstract needs to be submitted by May 4. 

[2021 AGU abstract](https://docs.google.com/document/d/1t9YiovmgTYa7OFHw_hyXsKLbRt87ruSF85dS-4QWwK4/edit)

[2021 AGU presentation](https://docs.google.com/presentation/d/1rWZpP76Z473vEhoihM65Z9gmOMny3LUTgrYz_MWj-Go/edit#slide=id.g51b31a8bdf_1_20)

[2020 AGU abstract](https://docs.google.com/document/d/1rszl5uV_yShGmkrzYElXGWgUJdOfKuORkYlKIuqw7OU/edit)

2020 MSFC Jamboree post attached: [APT_Jamboree2021_Poster.pptx](https://github.com/NASA-IMPACT/nasa-apt/files/11362188/APT_Jamboree2021_Poster.pptx)

### **Tasks:**
- [x] draft an abstract
- [x] have draft reviewed/edited
- [x] submit abstract/NOI

### **Acceptance Criteria:**
- [x] abstract/NOI submitted
