### ISSUE TITLE
Draft poster for jamboree

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#723]
### **Description**
[Abstract](https://docs.google.com/document/d/1sO-sdkS2ubxNLBrTyRi37IdyCQ3-J0oAALMoUIw0Sc4/edit) and Notice of Intent (NOI) was submitted to the MSFC STO Jamboree. The next step is to draft the poster.

Note: This will likely take several sprints. Adding deadline of June 5. STI due June 11. 
Most recent APT presentation [slides](https://docs.google.com/presentation/d/1qom33S_Yyu1gKPLuau3RhdUDD5CLDSndWTZKZSE8ybk/edit#slide=id.g23a8f504578_0_5). Much of this can be used on the poster. 

### **Tasks:**
- [x] Create an outline/structure of the [poster](https://docs.google.com/presentation/d/1OoC65vmp7fPzIIrDSkbawWo2ylqJfZmX7O85bYGuQnI/edit#slide=id.g169783234c8_0_0)
- [x] Add content
- [ ] Team reviews draft and makes edits/suggestions
- [ ] Poster is polished and finalized

### **Acceptance Criteria:**
- [ ] Digital version of poster is finished

**Comment by bwbaker1** [comment]
@ashleyriddle92 @cw0045 Let's try to keep track of how much time we spend on this so we can more accurately estimate the points.
