### ISSUE TITLE
Epic: Frontend changes to implement new design flow and deal with conditionality between document ATBDs and PDF ATBDs

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#726]
```[tasklist]
### Core Requirements
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/733
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/734
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/735
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/736
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/737
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/738
```
```[tasklist]
### Improvements
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/489
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/490
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/491
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/492
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/493
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/494
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/495
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/496
```

**Comment by bwbaker1** [comment]
@wrynearson Here are a couple of minor bugs I found while testing and two requests.


https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/8bca1524-755a-4d9b-8c13-1b5c26d5ef61

I forgot one thing in the video. Would it be possible from the create new atbd popup to change it to two buttons (see image below)? I'm not sure how difficult this would be, but it would make it much clearer to users. 
<img width="718" alt="Screen Shot 2023-06-08 at 8 26 24 AM" src="https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/59d779f3-e04b-4aa7-a0ba-35a78b539c68">

**Comment by wrynearson** [comment]
Thanks @bwbaker1! Videos like these are super helpful 🙏

1. Added here: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/493
2. Added here: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/494
3. Yes, we were talking about that internally. I added a ticket here https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/495. We were thinking that we could just link the uploaded PDF to the current download button. That way, users can have the download option in the same location and format, regardless of the "type" of ATBD that they're looking at. What do you think?

For the last point for the button-vs-toggle approach, that would be an easy change. However, I think this goes back to the question: do we treat the two workflows as equal options, or do we treat the PDF-upload workflow as an _alternative_ (secondary) option? My guess would be that we want to encourage users to use the standard workflow, but please let me know if you think differently.

Thanks for your detailed testing and review!

**Comment by bwbaker1** [comment]
@wrynearson For point #3, that's perfect! That's what I would prefer, but I wasn't sure if that was possible.

Button vs toggle: I think we have to treat both workflows as equal options at this point. I think two scenarios will happen. (1) A user already has an ATBD (PDF) when they go to create a document in APT. So their decision is already made. (2) A user that does not have an existing ATBD, in which case, I think most users will review creating a document both ways. I think the APT UI is more inviting than a template, but we have to remember that APT has had negative feedback internally for a while, which I think will influence decisions. Hopefully this changes moving forward. 

I got a couple other opinions about the button/toggle, and everyone seems to think that two buttons would be best. I'm up for a bigger discussion about this if you still feel strongly toward the toggle approach.

**Comment by wrynearson** [comment]
Thanks for the context. I don't feel strongly about it – it was more of a way for us to frame design choices now that could have effects later on. We'll go ahead with the button approach, which will be a good opportunity for A/B testing. Here's the new ticket: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/496
