### ISSUE TITLE
Draft email template for monthly APT Update

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#730]
### **Description**
Beginning this sprint, the APT curator will start sending out an APT "newsletter" type of email to all users. The idea is to keep in touch with users so that know we are supporting them, provide any interface updates/improvements that have been implemented, maybe give a general heads up of upcoming improvements (we must be very cautious if we mention these), and let them know to use the feedback form if they experience issues/or email the curator). 

^ Just brainstorming content ideas. This needs a team discussion.

### **Tasks:**
- [ ] discuss what type of content we should include
- [ ] design an [email template](https://docs.google.com/document/d/1aKeJ__lh7JZI5Ym7B0JHsXmFUextfUc8c3Nzy_Aj494/edit) (e.g., design section for monthly updates)
- [ ] create a group email (Brad - using NASA email)
- [ ] create bi-sprint issue as a reminder to send this email

### **Acceptance Criteria**
- [ ] Completed template is ready

**Comment by bwbaker1** [comment]
@ashleyriddle92 @cw0045 I will need help determining what content we should include and with creating a friendly design. We can discuss at our weekly tagup 5/15.

**Comment by wrynearson** [comment]
@bwbaker1 this is in sprint 1. Should this be moved to another sprint?

**Comment by bwbaker1** [comment]
@wrynearson I moved it.
