### ISSUE TITLE
Update landing page text

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#731]
### **Description**
Landing page text needs updating to reflect current state of APT. For example, journal submission is not "straightforward," therefore, the text needs to reflect that. A few other things needs updating/adjusting as well.

[Document](https://docs.google.com/document/d/1GO1lm8gM_NIyLkyvqeW1HphUlma7wfNfccIPQ7Ybf48/edit#heading=h.4ge3yvj4pk5r)

### **Tasks:**
- [x] review page and determine what updates are needed
- [x] send the updates to DevSeed

### **Acceptance Criteria**
- [x] landing page text updates sent to DevSeed

**Comment by bwbaker1** [comment]
@wrynearson The landing page updates are ready to be added to staging. [Document](https://docs.google.com/document/d/1GO1lm8gM_NIyLkyvqeW1HphUlma7wfNfccIPQ7Ybf48/edit#heading=h.4ge3yvj4pk5r)

**Comment by bwbaker1** [comment]
@wrynearson This looks good on staging.
