### ISSUE TITLE
Create table for benefits/drawbacks of publishing in journal vs apt

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#732]
### **Description**
Users may be confused on whether they should publish their ATBD in ESS or just in APT. We need to make the benefits and drawbacks of each very clear.

[Table](https://docs.google.com/document/d/1z6uPgQM65e1GqCCwJApVhwPRAhTKloSz6j2Mw1an8ag/edit)

### **Tasks:**
- [ ] create a table with the benefits and drawbacks of each
- [ ] determine where this table should go on the UI (probably at journal details)
- [ ] send to DevSeed for implementation

### **Acceptance Criteria:**
- [ ] table sent to DevSeed for implementation

**Comment by wrynearson** [comment]
@bwbaker1 what is ESS?

**Comment by bwbaker1** [comment]
@wrynearson This is the AGU journal option that we already have (ESS - Earth and Space Science). Sorry, I edited the description to AGU journal so that it's less confusing. The background for this issue is to help users know whether they should take the journal route or not.

**Comment by wrynearson** [comment]
Updating this content based on [this slide/comment](https://docs.google.com/presentation/d/1z0GKsChxL5OnQb1qUy2aYQxkVllZ_BT9ml7zoim20B8/edit?disco=AAAAzo9wlSY).

**Comment by wrynearson** [comment]
@bwbaker1 here's what the new table content will look like:

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/1b01a4d9-be0d-4d4d-9bf9-7609fa4b4e24)

Please let me know if I'm missing anything.

Regarding the APT User Interface drawback:
> User interface updates and improvements may cause intermitted disruptions

I understand where this is coming from 😅, but I'd recommend not stressing the fact that improvements will cause disruptions, since I'd imagine users would worry about data loss if they read this. Hopefully, updates and improvements are a good thing, not a negative

**Comment by bwbaker1** [comment]
@wrynearson This looks good. 

Go ahead and remove that bullet about disruptions. I don't think this is an issue anymore.
