### ISSUE TITLE
Update APT About Page Text

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#740]
### **Description**
About page text needs updating to reflect current state of APT. 

[Document](https://docs.google.com/document/d/1nzn_NBoDPrwVYq5BpP5IZcNH5JaDoOOrBcxKk9ukOfo/edit#heading=h.5fux3encqwtw)

### **Tasks:**
- [x] review page and determine what updates are needed
- [x] send the updates to DevSeed

### **Acceptance Criteria**
- [x] about page text updates sent to DevSeed

**Comment by bwbaker1** [comment]
@wrynearson The About page text is ready to be updated (see [document](https://docs.google.com/document/d/1nzn_NBoDPrwVYq5BpP5IZcNH5JaDoOOrBcxKk9ukOfo/edit)).

**Comment by bwbaker1** [comment]
@wrynearson Looks good on staging.
