### ISSUE TITLE
Not all email notifications are being triggered

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#748]
### **Description**
Not all email notifications are being triggered when specific actions are made. Notifications related to document transitions (e.g., curator notified when reviewers conclude review) is very important. These will be especially important soon as we have several ATBDs that will potentially be moving between stages. We want to ensure that the curator doesn't cause any user delays, but also ensure authors/reviewers are aware of where the documents stand. **For now, the curator can check the dashboard daily and send author/reviewers email if needed.**

[Spreadsheet](https://docs.google.com/spreadsheets/d/1uJ6t7_EUFzxrbXQmxugdjq5i_8i9O7Zi8P-LfcAeLbs/edit#gid=1986134040) - This sheet shows the higher priority notifications that need to be fixed/implemented.

### **Tasks:
- [x] determine why these specific notifications aren't working
- [x] implement fix
- [ ] test to ensure these are working after the fix

### **Acceptance Criteria**
- [ ] The 6 highlighted notifications are working on production and have been tested

**Comment by bwbaker1** [comment]
@wrynearson This will need to be our next priority following the PDF upload workflow. This was brought to my attention yesterday by a user. We can discuss further at our tagup June 5.

**Comment by wrynearson** [comment]
Sorry to hear that @bwbaker1. @thenav56, could you look into this when you get the chance?

**Comment by wrynearson** [comment]
Hi @bwbaker1, if you see this before our meeting today, could you give a few more details? Which user noticed this (and email address), and for which actions? Or is this list from internal testing?

@thenav56 tested this locally and didn't find anything wrong with the notification code itself. The issue is either coming from AWS or that the user's email domain is blocking the email. We had similar issues with SNWG for the latter reason.

We currently don't have `deny_publication_request` implemented on the frontend (i.e., that's not an action that authors can currently take, so we'll need to implement that in the frontend before that email is triggered.

**Comment by bwbaker1** [comment]
@wrynearson This is the document that first caught my attention ([[Chlorophyll a](https://www.earthdata.nasa.gov/apt/documents/chlor-a/v1.0)) (Guoqing Wang - guoqing.wang@nasa.gov). I didn't receive a notification when the author requested review. She reached out to me via email.

Then Camille and I tested internally (bwbaker1 - bwb0013@uah.edu and cw0045 - [cw0045@alumni.uah.edu](mailto:cw0045@alumni.uah.edu)). We tested all of the listed actions above and neither of us received notifications. We checked spam mailboxes as well.

**Comment by wrynearson** [comment]
OK thanks @bwbaker1, this is good to know. I'll chat with the team to look into this.

**Comment by sunu** [comment]
@bwbaker1 Do you have the approximate time for those actions? That would help us filter the logs.
@wrynearson since this is on production, we will need @naomatheus's help to look for the logs.

**Comment by bwbaker1** [comment]
@sunu Thanks for checking into this. The actions triggered by bwbaker1-bwb0013@uah.edu and cw0045-cw0045@alumni.uah.edu were on June 1 between 10am-1030am central standard time. 
I believe the actions triggered by Guoqing Wang/quoqing.wang@nasa.gov would have been sometime in early April. I received an email from her on April 12 stating that she had recently submitted her ATBD for review. Unfortunately, I am not 100% certain on this.

**Comment by wrynearson** [comment]
Hi @bwbaker1, we think that the email issues are related to AWS Simple Email Service (SES) account permissions. According to the [documentation](https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html), SES accounts are first placed in a "sandbox" which applies restrictions.  The number of emails that can be sent per 24h is limited to 200, which could be an issue in the future.

Most likely, the current issue is that emails can only be sent **to** and **from** verified email addresses. Is it possible that Guoqing's email is not verified in the system? If hers is verified, the issue could be that our email sending service isn't verified.

I'd suggest that someone at IMPACT requests to move your Amazon SES account out of the sandbox [by following these instructions](https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html#:~:text=To%20request%20that%20your%20account%20be%20removed%20from%20the%20Amazon%20SES%20sandbox%20using%20the%20AWS%20Management%20Console).

**Comment by bwbaker1** [comment]
@wrynearson I double-checked and Guoqing's email is verified.

@xhagrg @michaelsfoley  See [comment](https://github.com/NASA-IMPACT/nasa-apt/issues/748#issuecomment-1594185587). Is this something that either of you can help with? Or can you direct me to who could help?

**Comment by sunu** [comment]
We should also check that the sender email identity is verified. We had a [similar issue on SNWG ](https://github.com/NASA-IMPACT/snwg-script-project/issues/256#issuecomment-1359497157) that @xhagrg helped us fix by verifying the sender email address on SES

**Comment by wrynearson** [comment]
@xhagrg @bwbaker1 is there anything else we need to do on this ticket?

**Comment by bwbaker1** [comment]
@wrynearson I think this is done, but let us do some testing over the next few days. Will close if everything is working properly.

**Comment by bwbaker1** [comment]
@wrynearson I'm now aware that two notifications are not being triggered from users. 1. When document review is requested and 2. When document publication is requested.

I'm certain the document review request notification was working before.

**Comment by wrynearson** [comment]
@thenav56 would you have the chance to look into this?

@bwbaker1 I want to flag that on staging, your account is _both_ a contributor and a curator. If you were testing there with your account, that could explain why you weren't receiving some emails, but I'm not sure how both roles would interfere with each other in regards to email notifications.

<img width="294" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/b30b9086-1adf-4449-92de-e3eb082dbad6">

I did get the following notifications from `contributor1`:

<img width="1119" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/db47647f-173d-436a-8585-b3d2836d2c86">

**Comment by bwbaker1** [comment]
@wrynearson This is happening on production. A user requested a document be published, and I didn't receive anything. She sent me an email several days later asking to publish she. She also said that she did not get a notification when she made the request.

**Comment by wrynearson** [comment]
@bwbaker1 I would recommend that we find time to have DevSeed sync with you to be able to see the production logs, as we're having a difficult time debugging email notifications. There are many potential reasons for emails not being delivered, so we should first see if there's anything blocking us sending the emails in the first place.

**Comment by bwbaker1** [comment]
@wrynearson Sure. Let me know some day/times that works for you all and I will pick a time.

**Comment by wrynearson** [comment]
@leothomas @sunu @thenav56 (but I don't think all of you need to be there)

cc @batpad
