### ISSUE TITLE
Quick start guide

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#749]
### **Description**
We need a brief quick start user guide that lets users see how create an APT account, start a document, review a document, etc.

### **Tasks:**
- [x] draft the [document](https://docs.google.com/document/d/1wRIW_pACl7pKjqv7qDZehAJcCU-V2STBVZ2mHqD4DYw/edit)
- [x] review/edit guide
- [x] Place in markdown file on github

### **Acceptance Criteria:**
- [x] Provide DevSeed the quick start guide

**Comment by bwbaker1** [comment]
@wrynearson We will have this new guide done this sprint (S5). We will want to add this under the user guides tab with the Latex and APT user guides. Would it be easier for you if we just send you the markdown file when we are done?

**Comment by wrynearson** [comment]
Yes @bwbaker1, please send the file or post it here, and we'll get it uploaded.

**Comment by bwbaker1** [comment]
@wrynearson Here is the markdown file for the quick start guide. 

[APT_QuickStart.md](https://github.com/NASA-IMPACT/nasa-apt/files/11801182/APT_QuickStart.md)
