### ISSUE TITLE
Additional metadata information needed regarding ATBD Reviewers

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#753]
###**Description**
We need to collect reviewer information for each ATBD. If an ATBD has already been reviewed and is being uploaded, we need to be able to verify this review.

The reviewer information does not need to be included in ATBD search. 

My thinking is that this would be very similar to adding contacts (see below). However, we would only need the following:
First Name
Last Name
Email 
Affiliations

![Image](https://user-images.githubusercontent.com/56319064/244790000-7b5bc5e3-5a0d-4183-873b-10f6f3aa3803.png)

This will also solve our issue of informing the curator of who to contact about reviewing ATBDs created within APT. The curator could reach out to the potential reviewers via email with instructions on how to create an account.

### **Acceptance Criteria:**
- [ ] New step in APT (similar to Contacts) that requests above information about reviewers or potential reviewers
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/514
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/515
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/761
```

**Comment by bwbaker1** [comment]
@wrynearson This is just my thinking out loud. If it's too complicated/time consuming to make this an additional step in APT, we can just request this information somehow on the Identifying Information step.

**Comment by wrynearson** [comment]
Thanks @bwbaker1 for scoping this out. Do you see this being added only to the PDF-upload workflow, or also to the standard APT-created ATBD workflow?

Is there any way that you think we could incorporate this into the existing review process by encouraging external ATBD review to be done within the tool? Maybe that wouldn't make sense for historical ATBDs...

@thenav56 (or @sunu) and @frozenhelium, could you chime in on the LOE of adding this, either as a dedicated step or as an additional field?

**Comment by bwbaker1** [comment]
@wrynearson I see this for both workflows because we need reviewer information both ways.   

We still need this information even if the ATBD was reviewed externally (verification that it was actually reviewed). This includes historical ATBDs as well.

**Comment by sunu** [comment]
@bwbaker1 @wrynearson I have some questions to understand the intended workflow a little better:

1. Do we collect this information only for ATBDs that were externally reviewed already or for all ATBDs?
    1. If we collect this information for all ATBDs, will the curators use this information to assign reviewers for ATBDs that are yet to be reviewed? Should we also record whether an ATBD has already been reviewed externally or it needs review during ATBD creation?
2. Is this information visible to the authors and curators only or to all viewers?
3. For ATBDs that have been externally reviewed already, how does the verification process work for verifying that the ATBD was actually reviewed? Does it happen offline through email or inside APT?
    1. Does APT need a way to track this verification status somehow? eg: mark the reviewer information on an ATBD as verified or unverified?

**Comment by bwbaker1** [comment]
@wrynearson @sunu 

1. We are collecting this information for all ATBDs. 
    i. Yes, curators will use this information to assign reviewers.
    ii. Yes, it would be good to record whether the ATBD has been reviewed externally or needs review after creation/upload.
2. Yes, only the authors and curators need to know who the reviewers are.
3. The curator will simply email the reviewers to confirm/verify that it has been reviewed and is ready to be made public within APT.
    i. No, the curator will simply publish ATBDs that have been verified. We don't need this information on the ATBD. 

A couple of other points.
1. Just for clarification, none of the reviewer information needs to be generated on the PDFs. This is just for our own internal workflows.
2. It would be good to ask the user if the ATBD has already been: 1) submitted to a journal 2) published in a journal 3) or if they plan to submit to a journal. 
This is a little redundant for users completing their ATBDs within the APT interface (i.e., journal details section), but I think it is ok.

**Comment by wrynearson** [comment]
@kamicut @frozenhelium I'll break this down into several tickets

**Comment by wrynearson** [comment]
I added a few sub-tickets in the `tasks` list at the top of this ticket

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by wrynearson** [comment]
@frozenhelium I'm keeping this ticket open until we can get the reviewer information for PDF mode docs in view mode

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for testing on staging (in about 15 min)

**Comment by bwbaker1** [comment]
@wrynearson 

1. This looks good in view mode. Meaning I can see the reviewer info.
2. This looks good in PDF mode. Meaning the reviewer info is not displayed.
3. The only issue is that I can only add one reviewer. In theory, users should be able to add as many reviewers as they want. When I tested this before (a few sprints ago), I was able to add multiple reviewers. So something changed somewhere.

**Comment by kamicut** [comment]
@bwbaker1 @wrynearson after reviewing @frozenhelium's code and the ticket, I don’t think there was ever a case where there were “multiple reviewers” in that section. We merged in a PR where it was always the case where there was a single reviewer https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/528

Adding multiple reviewers will be a new UI/data component, and would require some work. I suggest that we re-use the existing "Contacts" form in this section to add reviewers. This would add less complexity to the code as the application wouldn't be managing and creating a list of contact information not tied to the existing "Contacts" backend.

To implement, we could re-use the "Roles related to this document" field that to mark the contact as a reviewer, for example ticking the `Writing - review & editing` checkbox. We could also use an explicit "Mark this contact as a reviewer" checkbox alongside the contact if that's more suitable.

Before implementing, we would need to answer the following questions related to the workflow:
1. Are "roles related to this document" used for the document presentation in any way? (view mode, journal, document PDF)?
2. What determines a contact show up in the "contact" section in the presentation? Should it be the simple fact of adding a contact that makes them show up? Or should it be required to select a role for this contact?
3. If we mark a contact as a reviewer should they also show up in the "Contacts" section in the view mode? If not, then is there a scenario where a contact shows up in the "Contacts" and "Reviewers" sections? 

Waiting for your feedback to implement the fix.

**Comment by wrynearson** [comment]
Thanks @kamicut. I confirmed with @bwbaker1 that this is a good approach. We should have a separate checkbox or radio button to select that someone is a reviewer (separate from `Writing - review & editing`). Being a reviewer on an individual report means that a contact would _not_ show up in the contacts section for that individual report. LMK if I missed anything @bwbaker1

**Comment by bwbaker1** [comment]
The section 9 "Reviewer Information" still shows up on the PDFs. It only needs to be on HTML.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. This is in review with https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/569

**Comment by wrynearson** [comment]
This is ready for your review @bwbaker1

**Comment by bwbaker1** [comment]
@wrynearson I am still seeing the reviewer info for both the journal and document PDFs.

<img width="587" alt="Screen Shot 2023-12-18 at 9 43 52 AM" src="https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/83d63af4-0db8-4ee7-be36-0a590b2b50cc">



<img width="587" alt="Screen Shot 2023-12-18 at 9 44 03 AM" src="https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/db8c59b3-aec3-4765-8d41-bedd57e03726">

**Comment by wrynearson** [comment]
We think this was a caching issue. I just checked after updating a document and both the Journal and Document PDFs don't have the `Reviewer Information` section, but the HTML does

**Comment by bwbaker1** [comment]
@wrynearson I just checked a document as well....and it worked as expected after making small update to the document. Thanks! I think this ticket is now complete, so feel free to close.
