### ISSUE TITLE
Submit AGU abstract

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#774]
### Description
Present recent updates and new user workflow to the American Geophysical Union Annual Conference.

### Tasks
- [ ] determine what session to submit to ([AGU 2023](https://www.agu.org/Fall-Meeting/Pages/Present/Abstracts))
- [ ] edit abstract from jamboree
- [ ] team review abstract/make final edits
- [ ] submit STI

### Acceptance Criteria
- [ ] abstract submitted to AGU
