### ISSUE TITLE
Submit AMS abstract

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#775]
### Description
Present recent updates and new user workflow to the American Meteorological Society Annual Conference.

### Tasks
- [ ] determine what session to submit to ([AMS 2024](https://annual.ametsoc.org/index.cfm/2024/program-events/call-for-papers/))
- [ ] edit abstract from jamboree
- [ ] team review abstract/make final edits
- [ ] submit STI

### Acceptance Criteria
- [ ] abstract submitted to AMS

**Comment by wrynearson** [comment]
@bwbaker1 this is in sprint 1. Should this be moved to another sprint?
