### ISSUE TITLE
Update slide deck to reflect current status of APT

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#776]
### **Description**
APT will likely present to science teams during the PI for potential adoption. The current slide deck needs to be updated to reflect recent changes to the interface and workflows.

### **Tasks**
- [x] Update the [slide deck](https://docs.google.com/presentation/d/1qom33S_Yyu1gKPLuau3RhdUDD5CLDSndWTZKZSE8ybk/edit#slide=id.g239606ab251_0_0)
- [x] Have team review changes

### **Acceptance Criteria**
- [ ] Finalized/updated slide deck
