### ISSUE TITLE
Inform users a new ATBD must have a title

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#779]

**Comment by bwbaker1** [comment]
### **Description**
When a user creates a new ATBD, they must add a title (can no longer be "Untitled document." However, users are not informed of this. If they try and create a document without changing the title, they are prompted with a 500 error. Similarly, an author cannot have two ATBDs with the same title; therefore, we also need to inform users that their title already exists.  



https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/ae504832-6b67-4eed-858c-688533650acb


### **Tasks:**
- [x] Option 1: add a popup that informs the user other than the 500 error code
- [ ] Option 2: add a text prompt that informs the user
- [ ] Option 3: TBD

### **Acceptance Criteria:**
- [ ] One of the above options is put into place to inform users. 

cc @wrynearson

**Comment by wrynearson** [comment]
Thanks Brad. @frozenhelium what do you think of adding a text field check when users create a new ATBD (similar to the check on image captions when we add images in ATBDs)?

**Comment by wrynearson** [comment]
We'll work on this in sprint 2.

**Comment by wrynearson** [comment]
Let's return more descriptive errors from the server, explaining that the alias is in use (before submitting form, when the user leaves focus on the text box)

**Comment by wrynearson** [comment]
We'll push this to next sprint.

**Comment by kamicut** [comment]
Noting here that the error is not descriptive enough on the server, and that we should provide a descriptive error from the backend as well @sunu

**Comment by sunu** [comment]
@kamicut - @thenav56 has added an explicit uniqueness check for the alias in the backend in #805. The backend should now return a 400 error code with this response: `{"detail":"Provided alias is not available"}`

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This works. However, I think some of our users will still be confused and think that the title must also be changed. I think it may be better to provide a little more detail in the error message. Maybe 
{"detail":"Your ATBD title is available. However, the provided alias is not available. Please provide a different alias."}

Or something along those lines.

**Comment by wrynearson** [comment]
@bwbaker1 this has been fixed

**Comment by bwbaker1** [comment]
@wrynearson Perfect! Ready for production.
