### ISSUE TITLE
FY24.2 Objective 2: Complete existing APT improvements

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#832]
## **Objective Statement**
Any P1 bugs identified during this quarter are given highest priority.

## **Motivation**
Ensure that users are not impeded by APT's functionality, existing or potential bugs, or knowledge of use. Any delay in ATBD development, those related to interface bugs and improvements deemed essential, creates user dissatisfaction with APT.

## **Description**
Known issues or identified bugs need to be completed and implemented. This list includes P1 bugs that may be identified early in the quarter. IMPACT will complete needed interface text and user guide updates and deliver these to DevSeed for implementation in the user interface. 

## **Acceptance Criteria**
- [x] Any P1 bugs are given the highest priority
- [x] Identified bugs from Q3 are fixed 
- [x] All tests are implemented
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/838
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/841
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/827#:~:text=section%20citations%20have-,extra,-commas%20%23827
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/830#:~:text=Encrypt%20all%20EBS-,Volumes,-%23830
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/784#:~:text=references%20should%20be-,enclosed,-by%20a%20single
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/825#:~:text=APT%20generated%20citations-,not,-formatted%20correctly%20%23825
```
