### ISSUE TITLE
FY24.3 Objective 4: Collect information for eventual transition to ESDIS

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#857]
## **Objective Statement**
Begin to prepare for a eventual transition of APT to ESDIS. 

## **Motivation**
The APT team wants to be prepared and have a plan in place for when the time comes to transition APT to ESDIS. Several details need to be determined so that the transition is as smooth as possible. 

## **Description**
The APT team will begin coordination with ESDIS and IMPACT management regarding the work that is needed for the eventual transition of APT to ESDIS. This will involve documenting all needed work and updating the curator guide. 

## **Acceptance Criteria**
- [ ] Update the curator user guide
- [ ] Work with ESDIS to determine what is needed for the transition
- [ ] Document all needed work for the transition
```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/860
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/861
```
