### ISSUE TITLE
FY24.4 Objective 1: Monitor APT to identify any bugs or issues

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#871]
## **Objective Statement**
Any P1 bugs identified during this quarter are given highest priority.

## **Motivation**
Ensure that users are not impeded by APT's functionality, existing or potential bugs, or knowledge of use. Any delay in ATBD development, those related to interface bugs and improvements deemed essential, creates user dissatisfaction with APT.

## **Description**
Known issues or identified bugs need to be completed and implemented. This list includes P1 bugs that may be identified early in the quarter. IMPACT will complete needed interface text and user guide updates and deliver these to DevSeed for implementation in the user interface. 

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/887
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/868
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/870
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/885
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/890
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/881
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/889
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/892
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/888
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/879
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/891
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/588
```
