### ISSUE TITLE
FY24.4 Objective 2: Complete user interface enhancements

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#872]
## **Objective Statement**
Enhance the user interface based on user feedback to optimize the overall user experience.  

## **Motivation**
Users have requested specific feature enhancements to improve writing ATBDs within APT. Additionally, there are PDF formatting issues that require attention. 

## **Description**
We need to complete a few carryover items from FY24.3, such as ensuring all ATBD titles are unique and restricting user access to their ATBDs (unless published). Additionally, make table, figure, and equation numbers visible in edit mode. 

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/759
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/863
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/858
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/825
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/896
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/784
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/827
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/849
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/878
```
