### ISSUE TITLE
FY24.4 Objective 3: Support users and promote APT

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#873]
## **Objective Statement**
Support all user needs and increase the knowledge of APT through various avenues such as presenting APT at science conferences and to science teams.

## **Motivation**
Ensure satisfactory use of APT and work towards increasing knowledge and understanding of APT for future users. Provide users with timely responses to account approvals, feedback, bugs, concerns, etc.

## **Description**
Use of APT is dependent on the knowledge of its existence, functionality, purpose, and usefulness. Educating APT users is vital to increasing its use and its effectiveness. This effort is to increase knowledge and use of APT.  In addition, this Objective includes instructing newly funded teams on APT use and educating NASA program scientists about APT availability and access. The UAH APT team will perform curator duties this quarter, including approving user accounts, assisting with questions, diagnosing problems, transitioning ATBDs from authoring to reviewing to release stages. 

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/869
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/874
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/875
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/876
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/877
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/842
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/897
```
