### ISSUE TITLE
FY25.1 Objective 2: Complete improvements to the user interface

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#902]
Objective Statement
Improve the user interface by incorporating user feedback to enhance the overall user experience.

Motivation
Users have identified specific feature enhancements to facilitate ATBD writing within APT, along with PDF formatting issues that need resolution.

Description
We need to address several outstanding items from FY24.4, including fixing backend caching issue (causes problem with some figures displaying), formatting discrepancies between Document and Journal PDF, and fix slight issue with the repository search function. 

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/907
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/908
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/909
```
